### PR TITLE
target-arch: decouple target arch from deb, and use a separate field …

### PR DESCRIPTION
**Pull request by piso77**
target field for better matching - aka introduce aliases for some archs

Signed-off-by: Paolo Pisati <paolo.pisati@canonical.com>

LP: #1674752

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
What would use the `target` field?

**Comment by piso77** [comment]
The kernel plugin, so i don't have to:

-set_snaparch() {
- # Attempt to find the correct architecture
- case "$UTS_MACHINE" in
- i386|ia64|alpha)
- snaparch="$UTS_MACHINE" ;;
- x86_64)
- snaparch=amd64 ;;
- sparc*)
- snaparch=sparc ;;
- s390*)
- snaparch=s390$(grep -q CONFIG_64BIT=y $KCONFIG_CONFIG && echo x || true) ;;
- ppc*)
- snaparch=$(grep -q CPU_LITTLE_ENDIAN=y $KCONFIG_CONFIG && echo ppc64el || echo powerpc) ;;
- parisc*)
- snaparch=hppa ;;
- mips*)
- snaparch=mips$(grep -q CPU_LITTLE_ENDIAN=y $KCONFIG_CONFIG && echo el || true) ;;
- aarch64)
- snaparch=arm64 ;;
- arm*)
- if grep -q CONFIG_AEABI=y $KCONFIG_CONFIG; then
- if grep -q CONFIG_VFP=y $KCONFIG_CONFIG; then
- snaparch=armhf
- else
- snaparch=armel
- fi
- else
- snaparch=arm
- fi
- ;;
- *)
- snaparch=$(dpkg --print-architecture)
- echo "" >&2
- echo "** ** ** WARNING ** ** **" >&2
- echo "" >&2
- echo "Your architecture doesn't have it's equivalent" >&2
- echo "Debian userspace architecture defined!" >&2
- echo "Falling back to using your current userspace instead!" >&2
- echo "Please add support for $UTS_MACHINE to ${0} ..." >&2
- echo "" >&2
- esac
- forcearch="--target-arch=$snaparch"
-}
-

just to convert from the $UTS_MACHINE arch (that is defined by the linux kernel kbuild system) to an equivalent deb ach

**Comment by kyrofa** [comment]
This seems reasonable to me. Let's run the autopkgtests.

**Comment by sergiusens** [comment]
@kalikiana this is supposed to live here, it is what we already supported once upon a time before moving to user space, it would however provide a good fallback.

**Pull request merged**
