### PR TITLE
kde extension: new content snap for core20

### PR DESCRIPTION
**Pull request by ppd**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----

See https://github.com/snapcore/snapcraft/pull/3658

### CODE REVIEW

**Comment by ppd** [comment]
I think the spread failure is because the content snap hasn't been declared auto-connectable yet.

**Comment by sergiusens** [comment]
Thanks for this, sorry for the late reply, I was mostly out enjoying some holidays the week prior and just catching up to things. Mind pinging once the snap is auto-connecting for me to retrigger the tests?

**Comment by ppd** [comment]
The request is here: https://forum.snapcraft.io/t/allow-global-auto-connect-for-kde-frameworks-5-96-qt-5-15-5-core20/31120
I'll ping you when it gets greenlighted.

**Comment by ppd** [comment]
> Mind pinging once the snap is auto-connecting for me to retrigger the tests?

@sergiusens Auto-connect has been granted.

**Comment by sergiusens** [comment]
do you want this released ASAP or do you want it to settle for a bit on edge?

**Comment by ppd** [comment]
It's a pretty boring update, and we've been publishing the official KDE snaps with it for a while. I'd say: release it soon.

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
