### PR TITLE
tests: report coverage only in unit tests

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by sergiusens** [comment]
this doesn't fix the spurious error when I run it locally though.

**Comment by sergiusens** [comment]
I still think you need to implement what is in my branch

**Comment by elopio** [comment]
@sergiusens ah, I see what you were getting at there. I copied your change here. We could have just landed both, sorry :)

**Comment by elopio** [comment]
Please don't land this branch yet. Coverage is not working because of:
`can use starred expression only as assignment target`

I think that's because codecov we have in travis is py2, and that's py3 syntax. Maybe, we can do everything in docker, I'll try.

**Comment by elopio** [comment]
Score! This is ready to go.

**Pull request merged**
