### PR TITLE
Ignore .tox directories when creating cleanbuild tar

### PR DESCRIPTION
**Pull request by OddBloke**
Thanks for helping us make a better Snapcraft!

Checklist:

- Have you signed the contributor licence agreement?
  https://www.ubuntu.com/legal/contributors

I'm a Canonical employee.

- Is there a reported a bug for the problem you are fixing?

LP: [#1661064](https://bugs.launchpad.net/snapcraft/+bug/1661064)

- Have you read our contribution guide?
  [CONTRIBUTING.md](CONTRIBUTING.md)

Yes.

### CODE REVIEW

**Comment by kyrofa** [comment]
As I commented on the bug, this approach doesn't seem to scale.

**Comment by sergiusens** [comment]
How about a .snapcraft_ignore that is consumed by everything (tar, local source, etc)?

**Comment by kyrofa** [comment]
> How about a .snapcraft_ignore that is consumed by everything (tar, local source, etc)?

Yeah, that was my suggestion on the bug. Shall we close this and have the conversation there?

**Comment by kyrofa** [comment]
I'll go ahead and close this. @OddBloke if you want to take a crack at the larger ignore feature, feel free to open another PR, or leave the bug and we'll get to it.

**Pull request closed without merging**
