### PR TITLE
rust plugin: fix linker on i386

### PR DESCRIPTION
**Pull request by dalance**
On i386 environment, linker becomes `i386-linux-gnu-gcc` according to
arch_triplet. It causes the following error on build.snapcraft.io:

```
error: linker `i386-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)
```

To fix it, I added `_get_linker` method to adjust linker name.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
Hi there, thank you for your contribution.
The _static_ tests for this PR are currently failing as we do require a signed CLA to be able to contribute, this is the current output:
```
dalance@gmail.com (https://api.launchpad.net/1.0/~dalance) has NOT signed the CLA
```

The checklist mentions you have signed the CLA though, if so, was it with another account?

**Comment by dalance** [comment]
The account is correct. At the time of CI, CLA may be under checking.
I received e-mail "You have been added to contributor-agreement-canonical" at 2019/6/5 14:37 UTC.
Could you re-run the check?

**Comment by sergiusens** [comment]
that did the trick @dalance

**Comment by sergiusens** [comment]
Failed tests are not relevant and being dealt with elsewhere:
- google:ubuntu-16.04-64:tests/spread/plugins/catkin/legacy-pull
- google:ubuntu-16.04-64:tests/spread/plugins/plainbox/provider-with-deps

**Pull request merged**
