### PR TITLE
Fix gnome extension g-ir-scanner PYTHONPATH

### PR DESCRIPTION
**Pull request by diddledani**
The sdk snap includes  executable which cannot find its python modules in their non-standard location.

* Add `/snap/<sdk snap>/current/usr/lib/<arch triplet>/gobject-introspection` to the `PYTHONPATH` variable in the build environment created by the gnome extension.

Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----

### CODE REVIEW

**Comment by diddledani** [comment]
force pushed to add the path into the test suite check `assert_get_part_snippet` and `test_get_part_snippet_with_external_sdk`.

**Comment by kenvandine** [comment]
This looks good to me

**Review by sergiusens — APPROVED** [review]

**Comment by sergiusens** [comment]
looks good, but there's a pylint issue

    snapcraft/extensions/gnome.py:237:0: C0301: Line too long (106/100) (line-too-long)

**Comment by diddledani** [comment]
All test errors (well linting errors at least - the tests were fine) fixed.

**Comment by sergio-costas** [comment]
I was to propose exactly this, because I found the same problem. So this also looks good to me.

**Pull request merged**
