### PR TITLE
remote-build: Add riscv64

### PR DESCRIPTION
**Pull request by cjwatson**
This architecture is now virtualized and unrestricted in Launchpad, so remote-build can support it.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----

### CODE REVIEW

**Comment by lengau** [comment]
This looks good internally — just one question before I approve

How does this interact with Launchpad's restrictions on riscv64 builds? (Or is this coming as a result of Launchpad opening riscv64?)

**Comment by cjwatson** [comment]
> How does this interact with Launchpad's restrictions on riscv64 builds? (Or is this coming as a result of Launchpad opening riscv64?)

This is a result of Launchpad opening riscv64, which we did today.

**Comment by mr-cal** [comment]
Looks like this failure was accidentally added by https://github.com/snapcore/snapcraft/pull/4431

I'll create a PR to fix it shortly and we can rebase this one.

**Review by lengau — APPROVED** [review]

**Comment by lengau** [comment]
> This is a result of Launchpad opening riscv64, which we did today.

**Review by mr-cal — APPROVED** [review]

**Comment by mr-cal** [comment]
The spread test is failing to fetch packages on random tests (4 failed runs in a row).  Going to try again another day

**Pull request merged**
