### PR TITLE
Add in command to list-parts, this could be useful to further enhance…

### PR DESCRIPTION
**Pull request by cwayne18**
… bash-completion

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
I like this @cwayne18, but it's missing tests.
It will require at least one unit test, like the ones you will find in snapcraft/tests/test_commands_*, and on integration test like the ones you will find in integration_tests/*

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
I am closing this as we discussed on irc a while way back then that we weren't looking forward to a top level non hidden `list-parts` command and we would much rather have this driven by envvars

**Pull request closed without merging**
