### PR TITLE
Feature/gradle plugin

### PR DESCRIPTION
**Pull request by ZenHarbinger**
Added an initial plugin for using gradle to build a Java project.

https://bugs.launchpad.net/snapcraft/+bug/1600492

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Looks good in general, I trust you can build gradle projects with this. :-)

One thing that needs to be done first is a rebase/merge and fix the conflicts

**Comment by ZenHarbinger** [comment]
too many files, I'm not totally w/ git all the time.
I'll re-base and re submit a PR.

**Pull request closed without merging**
