### PR TITLE
Use --force-dangerous when testing the installation of snaps

### PR DESCRIPTION
**Pull request by elopio**
LP: #1621535

### CODE REVIEW

**Comment by ogra1** [comment]
--force-dangerous is deprecated (that was fast, eh ?) it is just called --dangerous now

**Comment by elopio** [comment]
@ogra1 fast, but didn't make it into xenial-updates yet. We will need another similar branch next week.

**Comment by kyrofa** [comment]
@ogra1 there's deprecated, and then there's just completely removed :stuck_out_tongue: .

**Comment by sergiusens** [comment]
:cry:

**Pull request merged**
