### PR TITLE
Add snapcraft plugin for Qt Build Suite (qbs)

### PR DESCRIPTION
**Pull request by bjorn**
This plugin supports building any applications that use gcc or clang toolchains, as well as Qt(4&5) based applications.

I've revived it from #1079, first start is just to cherry-pick the change that was reverted later and to resolve the conflicts. Then I ran `black .` to fix up the coding style and made some further changes to make static tests pass.

LP: [#1659537](https://bugs.launchpad.net/snapcraft/+bug/1659537)

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?
  * Doesn't work yet (see output below)

-----

`./runtests.sh static` outputs:

```
Running black
All done! ✨ 🍰 ✨
612 files would be left unchanged.
Running flake8
Running mypy
Running codespell
./tests/spread/plugins/rust/snaps/rust-workspace-fib/calc-fib/src/main.rs:2: crate  ==> create, crate
./tests/spread/plugins/rust/snaps/rust-with-conditional/src/main.rs:1: crate  ==> create, crate
WARNING: Binary file: ./tests/spread/general/invalid-elf/snaps/invalid_elf/corrupt_empty.elf64.so 
WARNING: Binary file: ./tests/spread/general/invalid-elf/snaps/invalid_elf/corrupt_unicode.elf64.so 
```

(seems unrelated to Qbs plugin, so assuming this is a successful run)

`./runtests.sh tests/unit` outputs:

```
======================================================================
FAIL: test_schema (tests.unit.plugins.test_qbs.QbsPluginTestCase)
tests.unit.plugins.test_qbs.QbsPluginTestCase.test_schema
----------------------------------------------------------------------
testtools.testresult.real._StringException: Empty attachments:
  pythonlogging:''

Traceback (most recent call last):
  File "/home/ubuntu/snapcraft/tests/unit/plugins/test_qbs.py", line 149, in test_schema
    'Expected schema to include "build-properties"',
  File "/home/ubuntu/.venv/snapcraft/lib/python3.6/site-packages/unittest2/case.py", line 702, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Expected schema to include "build-properties"
```

### CODE REVIEW

**Comment by cjp256** [comment]
Sorry for the delay, been a busy few weeks.


1. For the CLA, you may use `sergio.schvezov` __at__`canonical.com`
2. I've updated the branch.
3. You would have the best luck testing snapcraft is using the `snapcraft-dev` container created by `tools/environment-setup.sh`.  That will ensure your dependencies are locked in with ours.

I haven't looked at this closely yet, but the biggest thing I see is that we need to convert the integration tests to spread tests.

**Comment by bjorn** [comment]
@cjp256 It seems your merge undid some changes that were included here to fix the static unit tests based on black formatting. Now it again reports:
```
unning black
--- snapcraft/plugins/_ros/wstool.py	2020-01-24 22:05:51.351079 +0000
+++ snapcraft/plugins/_ros/wstool.py	2020-02-12 16:25:48.521581 +0000
@@ -164,19 +164,18 @@
         env["PATH"] += ":" + os.path.join(self._wstool_install_path, "usr", "bin")
 
         if "LD_LIBRARY_PATH" in env:
             env["LD_LIBRARY_PATH"] += ":"
         ld_library_path = env.get("LD_LIBRARY_PATH", "")
-        env["LD_LIBRARY_PATH"] = (
-            ld_library_path
-            + snapcraft.formatting_utils.combine_paths(
-                snapcraft.common.get_library_paths(
-                    self._wstool_install_path, self._project.arch_triplet
-                ),
-                prepend="",
-                separator=":",
-            )
+        env[
+            "LD_LIBRARY_PATH"
+        ] = ld_library_path + snapcraft.formatting_utils.combine_paths(
+            snapcraft.common.get_library_paths(
+                self._wstool_install_path, self._project.arch_triplet
+            ),
+            prepend="",
+            separator=":",
         )
 
         # Make sure git can be used out of the wstool install path instead of needing
         # to be a build-package
         env["GIT_EXEC_PATH"] = os.path.join(
would reformat snapcraft/plugins/_ros/wstool.py
--- snapcraft/plugins/dotnet.py	2020-01-24 22:05:51.351079 +0000
+++ snapcraft/plugins/dotnet.py	2020-02-12 16:25:48.823376 +0000
@@ -41,13 +41,11 @@
 from snapcraft import formatting_utils
 from snapcraft.internal import errors
 from typing import List
 
 
-_DOTNET_RELEASE_METADATA_URL = (
-    "https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json"
-)  # noqa
+_DOTNET_RELEASE_METADATA_URL = "https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json"  # noqa
 _RUNTIME_DEFAULT = "2.0.5"
 
 # TODO extend for other architectures
 _SDK_ARCH = ["amd64"]
 
would reformat snapcraft/plugins/dotnet.py
Oh no! 💥 💔 💥
2 files would be reformatted, 612 files would be left unchanged.
```
Maybe a separate pull request should be opened to fix those issues.

Running the unit tests in the `snapcraft-dev` environment worked much better. I've updated the status in the original post. Right now I don't know why the Qbs expects schema to include "build-properties".

**Comment by cjp256** [comment]
Ah, yes.  The `black` formatting is due to a version discrepancy.

Try:
`sudo snap refresh black --beta`

Or do that in snapcraft-dev?

Yeah, that test_schema is a bit excessive. I would maybe replace the whole blob with something that accomplishes the same thing, but in one go, such as (untested):

```
def test_schema(self):
        expected_schema = {'$schema': 'http://json-schema.org/draft-04/schema#', 'type': 'object', 'additionalProperties': False, 'properties': {'qbs-build-variant': {'enum': ['debug', 'release'], 'default': 'release'}, 'qbs-options': {'type': 'array', 'minitems': 1, 'uniqueItems': True, 'items': {'type': 'string'}, 'default': []}, 'qbs-profile': {'enum': ['gcc', 'clang'], 'default': 'gcc'}, 'qt-version': {'enum': ['qt4', 'qt5'], 'default': None}}}
        schema = qbs.QbsPlugin.schema()
        self.assertThat(schema, Equals(expected_schema))
```

**Comment by sergiusens** [comment]
While we appreciate the contribution, it seems this PR has gone stale. Feel free to reopen once ready.

**Comment by bjorn** [comment]
@sergiusens Unfortunately I have not much Python experience and neither much time to dig into Snapcraft so converting the integration tests to spread tests is not feasible for me. Is there no interest in this plugin from the Snapcraft team?

**Pull request closed without merging**
