### PR TITLE
New plugin: grunt

### PR DESCRIPTION
**Pull request by mariogrip**
This is based of #563 and uses code from it.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
Hello @mariogrip, it's great to have new contributors :)

Can you please sign the contributors agreement? http://www.ubuntu.com/legal/contributors
If you have any questions not covered in there, please let us know.

This branch is missing unit tests for the plugin, and at least one integration test. Sergio's branch has the unit tests to give you an idea of what we want in there, and will soon have the integration test added too. If you need a hand with this, we are here to help.

pura vida.

**Comment by mariogrip** [comment]
@elopio I was about to sign the contributors agreement, but i got stuck on "Please add the Canonical Project Manager or contact" who should set as Project Manager or contact person?

**Comment by sergiusens** [comment]
@mariogrip hi, looks good, thanks for working on this. Can we get unit tests going for this please (it can be mostly a copy from the gulp ones).

I would also like a review from @cwayne18 who worked with grunt a bit to get atom working

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by elopio** [comment]
@mariogrip hey, sorry, I missed your question. The manager for our project is Jamie Bennet.

**Comment by cwayne18** [comment]
One thing that I'd found helpful when I did a one-off grunt plugin was having an option to point to the gruntfile itself, in case it's in a different build/ dir

**Comment by kyrofa** [comment]
This has been sitting for a while with no progress, so I'll go ahead and close it. @mariogrip please feel free to reopen when you're ready to respond to @cwayne18's review, as well as sign the CLA.

**Pull request closed without merging**
