### PR TITLE
sanity checks: allow snap/local dir

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

It's natural for folks to want to put all snap-specific files into the `snap/` directory. This PR resolves [LP: #1792203](https://bugs.launchpad.net/snapcraft/+bug/1792203) by giving them a place to do that: `snap/local/`.

### CODE REVIEW

**Comment by sergiusens** [comment]
tests fail for real here

**Comment by Lin-Buo-Ren** [comment]
Refer [snapcrafters-template-plus/snap at master · Lin-Buo-Ren/snapcrafters-template-plus](https://github.com/Lin-Buo-Ren/snapcrafters-template-plus/tree/master/snap) for an example of the usage of the `snap` directory.

It's not quite sane to put snap-specific files in a separate directory in the source tree, this PR can be a solution ~~(or compromise)~~

**Comment by kyrofa** [comment]
@Lin-Buo-Ren indeed, if you want those sources within the snap folder, you'll need to put them in `snap/local/`. The behavior will be enshrined in tests once this lands, but you should be able to safely do that today.

**Comment by sergiusens** [comment]
@kyrofa I made the tests a bit more deterministic, in the sense that if there is a bug on "sort" we are not hit by it :-)

**Comment by kyrofa** [comment]
Haha, thanks @sergiusens, what a weird issue. Looks good to me.

**Comment by Lin-Buo-Ren** [comment]
I've tried the snapcraft in edge channel today and notice the following warning message:

```
The snap/ directory is meant specifically for snapcraft, but it contains the following non-snapcraft-related paths, which is unsupported and will cause unexpected behavior:
- .editorconfig
- .gitignore

If you must store these files within the snap/ directory, move them to snap/local/, which is ignored by snapcraft.
```

as you can see these files are not possible to be moved to the `snap/local` directory because of it applies to the `snap` directory itself (not all upstream prefer stuff applies to a single directory be put under the root of the source tree).  I would like to request to increase the allowable area to include dot files and even README* files for customization and documenting purposes.

**Pull request merged**
