### PR TITLE
Improve python2 test coverage

### PR DESCRIPTION
**Pull request by SamYaple**
LP:#1603437

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
CLA verified.

**Comment by kyrofa** [comment]
ok to test

**Comment by kyrofa** [comment]
retest this please

**Comment by kyrofa** [comment]
retest this please

**Comment by sergiusens** [comment]
thanks for your contribution.

**Pull request merged**
