### PR TITLE
ua: add support to ua token management

### PR DESCRIPTION
**Pull request by cmatsuoka**
Attach and detach the build host, vm or container to an Ubuntu
Advantage subscription by passing a UA authentication token using
the `--ua-token` command-line argument or the `SNAPCRAFT_UA_TOKEN`
environment variable.

Co-authored-by: Chris Patterson <chris.patterson@canonical.com>
Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----
CRAFT-1288

### CODE REVIEW

**Comment by sergiusens** [comment]
@artivis and @Guillaumebeuzeboc

**Comment by cmatsuoka** [comment]
This PR doesn't enable services, it just ports the legacy UA manager that works only with the default services. Enabling services will be handled in the next PR.

**Comment by cmatsuoka** [comment]
> I wanted to give it a shot, but it doesn't work with test tokens right (staging token)? `/etc/ubuntu-advantage/uaclient.conf` would have to be modified, and the `ua attach` is happening before the `pull` step.

I think you'll need to let it fail, enter the container/vm, edit the file, and then run snapcraft again reusing the container.

**Comment by Guillaumebeuzeboc** [comment]
> > I wanted to give it a shot, but it doesn't work with test tokens right (staging token)? `/etc/ubuntu-advantage/uaclient.conf` would have to be modified, and the `ua attach` is happening before the `pull` step.
> 
> I think you'll need to let it fail, enter the container/vm, edit the file, and then run snapcraft again reusing the container.

Indeed, by letting it fail, I could change it. I successfully attach the token.

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
