### PR TITLE
Add core20 support to the Flutter extensions

### PR DESCRIPTION
**Pull request by AlanGriffiths**
- [X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Review by sergiusens — DISMISSED** [review]

**Comment by sergiusens** [comment]
@kenvandine is this ok with you?

**Comment by sergiusens** [comment]
I talked to @kenvandine, we might need a base specific sdk snap for this, will wait on his further input

**Comment by kenvandine** [comment]
I have a WIP branch converting the flutter snap to core20.  Due to the nature of the flutter snap, it would be desirable to have the extension choose which flutter snap to use depending on which base is specified.  I'm thinking of publishing the core18 build of flutter to a new track before merging the core20 PR and publishing that to stable.

**Comment by AlanGriffiths** [comment]
> I have a WIP branch converting the flutter snap to core20

@kenvandine just checking you realise the purpose of this PR is far less ambitious. It doesn't deal with the flutter build plugin, just with the extension providing the runtime environment. (We both know it is possible to build Flutter apps on 20.04, and do so "by hand" in a core20 snap, this was just a drive-by offering to make it simpler to run afterwards.)

**Comment by sergiusens** [comment]
Thanks Alan, but I believe I am going to follow Ken's lead on this one and wait for the final solution as it might be too hard to extend the extension without breaking things for anyone adopting it early.

**Comment by AlanGriffiths** [comment]
:shrug: It is easy enough to do the same "by hand" instead of using the extension. (I copied that from Ken.)

**Comment by sgehrman** [comment]
"It is easy enough to do the same "by hand" instead of using the extension"
Where is there an example?

**Comment by kenvandine** [comment]
Here's an example for core22 https://github.com/canonical/workshops/blob/main/snap/snapcraft.yaml

**Comment by AlanGriffiths** [comment]
And for core20: https://github.com/MirServer/iot-example-graphical-snap/tree/Flutter-demo

**Comment by sgehrman** [comment]
@kenvandine 
 sudo snap install driftwood_1.0.0_amd64.snap --dangerous --devmode
2022-12-07T04:37:37-08:00 INFO snap "driftwood" has bad plugs or slots: ldx (unknown interface "ldx")
2022-12-07T04:37:38-08:00 INFO snap "driftwood" has bad plugs or slots: ldx (unknown interface "ldx")
driftwood 1.0.0 installed
WARNING: There is 1 new warning. See 'snap warnings'.
steve@5950x:~/Documents/GitHub/dfc/dashboard$ driftwood

(driftwood:45090): dbind-WARNING **: 04:37:51.927: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-4bCTsHYlON: No such file or directory

** (driftwood:45090): WARNING **: 04:37:52.126: Failed to start Flutter renderer: No available configurations for the given RGBA pixel format

**Comment by sgehrman** [comment]
@kenvandine 

$ sudo snap install driftwood_1.0.0_amd64.snap --dangerous --devmode
driftwood 1.0.0 installed
WARNING: There is 1 new warning. See 'snap warnings'.
steve@5950x:~/Documents/GitHub/dfc/dashboard$ driftwood

(driftwood:51354): dbind-WARNING **: 04:41:18.692: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-4bCTsHYlON: No such file or directory

** (driftwood:51354): WARNING **: 04:41:18.771: Failed to start Flutter renderer: No available configurations for the given RGBA pixel format

**Comment by sgehrman** [comment]
tried: snap set snapcraft provider=multipass

Launching instance... - (248.5s)                                                                                                                                                                                                        Traceback (most recent call last):
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/actions/snap_installer.py", line 320, in inject_from_host
    executor.execute_run(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/multipass/multipass_instance.py", line 200, in execute_run
    return self._multipass.exec(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/multipass/multipass.py", line 113, in exec
    return runner(final_cmd, **kwargs)  # pylint: disable=subprocess-run-check
  File "/snap/snapcraft/8619/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['multipass', 'exec', 'snapcraft-driftwood-on-amd64-for-amd64-32907655', '--', 'sudo', '-H', '--', 'snap', 'install', '/tmp/snapcraft.snap', '--classic']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 480, in _install_snaps
    snap_installer.inject_from_host(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/actions/snap_installer.py", line 328, in inject_from_host
    raise SnapInstallationError(
craft_providers.actions.snap_installer.SnapInstallationError: failed to install snap 'snapcraft'
* Command that failed: 'multipass exec snapcraft-driftwood-on-amd64-for-amd64-32907655 -- sudo -H -- snap install /tmp/snapcraft.snap --classic'
* Command exit code: 1
* Command standard error output: b'error: cannot perform the following tasks:\n- Ensure prerequisites for "snapcraft" are available (cannot install snap base "core20": Post "https://api.snapcraft.io/v2/snaps/refresh": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers))\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/multipass/multipass_provider.py", line 105, in launched_environment
    instance = launch(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/multipass/_launch.py", line 82, in launch
    base_configuration.setup(executor=instance)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 354, in setup
    self._install_snaps(executor=executor, deadline=deadline)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/bases/buildd.py", line 486, in _install_snaps
    raise BaseConfigurationError(
craft_providers.bases.errors.BaseConfigurationError: failed to inject host's snap 'snapcraft' into target environment.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/snapcraft/8619/bin/snapcraft", line 8, in <module>
    sys.exit(run())
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/cli.py", line 228, in run
    _run_dispatcher(dispatcher)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/cli.py", line 204, in _run_dispatcher
    dispatcher.run()
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_cli/dispatcher.py", line 448, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/commands/lifecycle.py", line 259, in run
    super().run(parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/commands/lifecycle.py", line 132, in run
    parts_lifecycle.run(self.name, parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 208, in run
    _run_command(
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 249, in _run_command
    _run_in_provider(project, command_name, parsed_args)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 530, in _run_in_provider
    with provider.launched_environment(
  File "/snap/snapcraft/8619/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/snap/snapcraft/8619/lib/python3.8/site-packages/craft_providers/multipass/multipass_provider.py", line 115, in launched_environment
    raise MultipassError(str(error)) from error
craft_providers.multipass.errors.MultipassError: failed to inject host's snap 'snapcraft' into target environment.

**Comment by mr-cal** [comment]
Hi @sgehrman,

That error log looks more like a connection issue with snapcraft.io, specifically this line: `(cannot install snap base "core20": Post "https://api.snapcraft.io/v2/snaps/refresh":net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers))\n'`

It could have been a temporary network problem and may work now.  You may also need to run `snapcraft clean` to start with a new multipass instance.  Otherwise, it may be a legitimate network issue.

**Comment by sgehrman** [comment]
Thanks, I ran it again. I got a different failure.  I'll keep trying things, but here's what I got.
@mr-cal 

2022-12-08 15:30:02.608 :: 2022-12-08 15:29:25.846 :: [  +10 ms] Building Linux application...
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:25.851 :: [   +5 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64 /root/parts/driftwood/build/linux
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.044 :: [ +192 ms] -- The CXX compiler identification is Clang 14.0.0
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.050 :: [   +7 ms] -- Detecting CXX compiler ABI info
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.155 :: [ +103 ms] -- Detecting CXX compiler ABI info - done
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.158 :: [   +3 ms] -- Check for working CXX compiler: /usr/bin/clang++ - skipped
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.159 :: [        ] -- Detecting CXX compile features
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.159 :: [        ] -- Detecting CXX compile features - done
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.163 :: [   +3 ms] -- Found PkgConfig: /snap/gnome-42-2204-sdk/current/usr/bin/pkg-config (found version "0.29.2")
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.164 :: [        ] -- Checking for module 'gtk+-3.0'
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.174 :: [  +10 ms] --   Found gtk+-3.0, version 3.24.34
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.211 :: [  +36 ms] -- Checking for module 'glib-2.0'
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.216 :: [   +5 ms] --   Found glib-2.0, version 2.74.0
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.227 :: [  +10 ms] -- Checking for module 'gio-2.0'
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.232 :: [   +5 ms] --   Found gio-2.0, version 2.74.0
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.254 :: [  +21 ms] -- Checking for module 'ayatana-appindicator3-0.1'
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.267 :: [  +12 ms] --   Found ayatana-appindicator3-0.1, version 0.5.90
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.318 :: [  +51 ms] -- Configuring done
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.409 :: [  +90 ms] -- Generating done
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.413 :: [   +4 ms] -- Build files have been written to: /root/parts/driftwood/build/build/linux/x64/release
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.420 :: [   +6 ms] executing: ninja -C build/linux/x64/release install
2022-12-08 15:30:02.608 :: 2022-12-08 15:29:26.427 :: [   +7 ms] ninja: Entering directory `build/linux/x64/release'
2022-12-08 15:30:02.608 :: 2022-12-08 15:30:00.464 :: [+34036 ms] [1/16] Generating /root/parts/driftwood/build/linux/flutter/ephemeral/libflutter_linux_gtk.so, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_engine.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_call.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_value.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_view.h, /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
2022-12-08 15:30:02.608 :: 2022-12-08 15:30:00.484 :: [   +2 ms] FAILED: /root/parts/driftwood/build/linux/flutter/ephemeral/libflutter_linux_gtk.so /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_engine.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_call.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_method_response.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_value.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/fl_view.h /root/parts/driftwood/build/linux/flutter/ephemeral/flutter_linux/flutter_linux.h flutter/_phony_ /root/parts/driftwood/build/build/linux/x64/release/flutter/_phony_

---

2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.512 :: [        ] [+32420 ms] Persisting file store
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.512 :: [        ] [   +2 ms] Done persisting file store
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.512 :: [        ] [   +2 ms] Target kernel_snapshot failed: Exception
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.512 :: [        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:244:7)
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.513 :: [        ]            <asynchronous suspension>
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.513 :: [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.513 :: [        ]            <asynchronous suspension>
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.513 :: [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.513 :: [        ]            <asynchronous suspension>
2022-12-08 15:30:02.609 :: 2022-12-08 15:30:00.514 :: [        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)

**Comment by sgehrman** [comment]
might be related.  https://forum.snapcraft.io/t/creating-snap-error-in-flutter/31290

I think I read on github this is a 'refresh' bug or something.

**Comment by sgehrman** [comment]
Trying the lxd version again.  I got "No available configurations for the given RGBA pixel format"

And tried :  $ GTK_DEBUG=interactive driftwood

Looks like I'm missing some check marks. Anyone know how to fix that?

gnome-shell-screenshot-UCT5W1

**Comment by sgehrman** [comment]
Found this command:  $ LIBGL_DEBUG=verbose /snap/bin/driftwood --verbose

libGL: WARNING: unknown fbconfig attribute from server: tag 0x20b3 value 0x0
(repeated a bunch)

libGL: screen 0 does not appear to be DRI2 capable
libGL: MESA-LOADER: dlopen(/snap/driftwood/x1/gnome-platform/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/steve/snap/driftwood/x1/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/steve/snap/driftwood/x1/.drirc: No such file or directory.
libGL: Not downgrading visual rating
libGL: Disabling server's aux buffer support
libGL: Disabling server's tfp mipmap support

**Comment by sgehrman** [comment]
$ LIBGL_DEBUG=verbose /snap/driftwood/current/bin/driftwood --verbose
/snap/driftwood/current/bin/driftwood: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/driftwood/current/bin/driftwood)

**Comment by sgehrman** [comment]
Giving up. snap is too buggy.  Going to try flatpak.

**Pull request closed without merging**
