### PR TITLE
Add constraints to python2 plugin

### PR DESCRIPTION
**Pull request by SamYaple**
LP:#1603110

There is currently no support for constraints[1] files with the python2 plugin. Some projects make heavy use of constraints. OpenStack is one such project

[1] https://pip.pypa.io/en/stable/user_guide/#constraints-files

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by SamYaple** [comment]
this PR is waiting for other PRs which improve the test coverage of the python2 module, at that point this will be rebased

**Comment by sergiusens** [comment]
unit tests failed here

**Comment by sergiusens** [comment]
but good work so far :-)

**Comment by sergiusens** [comment]
`snapcraft/plugins/python2.py:126:1: C901 'Python2Plugin._pip' is too complex (10)`

`./runtests.sh static` to reproduce locally

**Comment by javacruft** [comment]
It would be nice if the python3 plugin could support constraints as well - it has general applicability across pip installations.

We might want to rework the python plugins a bit to have a common base - I can see alot of common code.

**Comment by SamYaple** [comment]
@javacruft thats next, want to get this working and approved before implementing py3 patch

**Comment by SamYaple** [comment]
@sergiusens running locally doesnt produce that error for complexity, even after rebase onto master. I probably havent pushed something up so ill check on it.

**Comment by sergiusens** [comment]
ok to test

**Comment by sergiusens** [comment]
Thanks for this

**Pull request merged**
