### PR TITLE
requirements: uprev lxml to 4.5.0

### PR DESCRIPTION
**Pull request by cjp256**
Should now fetch wheel for Windows and Linux.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>

- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by cjp256** [comment]
Looks it it builds fine without those stage packages.  Removed!

**Comment by sergiusens** [comment]
Are we sure we are using C bindings and not some slower implementation in python by going down this path?

**Comment by cjp256** [comment]
I don't think so.  But I think my original PR made the most sense, so I'm going to restore that.

Even if we don't need the `-dev` packages, I think we should still install them (in case the wheel becomes no longer available).

It's probably picking up libxml2 and xslt from the host.

**Comment by cjp256** [comment]
Tested the latest push (w/o xslt and xml libs) against #2952 to verify appstream is OK after removal in a minimal env.

**Pull request merged**
