### PR TITLE
Add detection for an existing `.snapcraft.yaml` file before running `snapcraft init`

### PR DESCRIPTION
**Pull request by tsimonq2**
(This fixes bug [1604326](https://pad.lv/1604326))

This ensures that an extra `snapcraft.yaml` isn't created when a `.snapcraft.yaml` file already exists.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Thanks for the quick fix.
I would appreciate a unit test for this though

**Comment by tsimonq2** [comment]
@sergiusens this now has a unit test

**Pull request merged**
