### PR TITLE
Update the Standards-Versions and the Vcs* tags in the debian/control file

### PR DESCRIPTION
**Pull request by tsimonq2**
This makes a couple changes:
 * Bumped `Standards-Version` to `3.9.8`
 * Change the URL in `Vcs-Git` to have `.git` at the end
 * Add the `Vcs-Browser` field with the GitHub URL

@sergiusens is the one who publishes the Snapcraft packages, could you review this please?

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
The title of this PR is rather un-explanatory :wink: .

**Comment by tsimonq2** [comment]
bump

**Pull request merged**
