### PR TITLE
tests: move test files out of the snapcraft dir

### PR DESCRIPTION
**Pull request by elopio**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by elopio** [comment]
This diff is aweful, but I did it with git mv :man_shrugging: 
I guess we will have to trust the tests. I was very careful while doing it, only removed `snapcraft.` and updated the copyrights. So, it should be very safe, and any breakages should appear on the test execution.

**Comment by elopio** [comment]
@kalikiana no, we can't get rid of any dependencies. What Sergio said is that we should start duplicating the helpers in the tests package.

**Comment by kyrofa** [comment]
@elopio yeah, github isn't super smart with moves. I bet if you ran a simple `git diff` it would be much prettier.

**Comment by kyrofa** [comment]
I think we have amd64/i386 back now, it'd be nice to see an autopkgtest run on this.

**Comment by elopio** [comment]
This conflict is too scary. I will try to make the move again instead.

**Pull request closed without merging**
