### PR TITLE
demo files for snaping the bitcoin-qt client

### PR DESCRIPTION
**Pull request by torusJKL**
If applied, this commit will add an additional demo for building the BerkleyDB and the Bitcoin Unlimited Qt client.
The demo shows how files from a part can be copied to the staging area and used for building later parts.

### CODE REVIEW

**Comment by elopio** [comment]
Hey @torusJKL! Thanks for your PR. I was thinking that this might be better as a tutorial: how to snap bitcoin, or something like that. https://tutorials.ubuntu.com/
We would have to ask the marketing team if that falls into their plan for tutorials. But what do you think?

**Comment by torusJKL** [comment]
Hi @elopio 
No problem.
Please let me know what the marketing team thinks about it.

**Comment by elopio** [comment]
@torusJKL they said it would be an interesting topic. Would you like to write that tutorial?
@didrocks would help you with the styling required for the tutorial, and I can help you with the snapcraft parts, or anything else you need. I would love this :)

**Comment by torusJKL** [comment]
Hi @elopio @didrocks 
I'm very interested to write the tutorial. I have set up a jabber server to communicate more easily.
Did you get my message on jabber?

**Comment by didrocks** [comment]
I don't think we should do a demo on how to snap a particular application, but rather, abstract the concepts that we don't cover in tutorials yet and using that snap as an example for this. I'm on IRC (freenode, #snappy) if you want to discuss about it :)

**Comment by elopio** [comment]
@torusJKL my jabber server has been offline for at least 5 years. We are currently using rocket.ubuntu.com, or IRC to communicate.

**Comment by elopio** [comment]
I'm closing this as now we have a plan to turn it into a tutorial with the help of didrock and torusJKL.

**Pull request closed without merging**
