### PR TITLE
Add `snapcraft history` and `snapcraft status`.

### PR DESCRIPTION
**Pull request by maxiberta**
Add `snapcraft history` and `snapcraft status` subcommands following discussed specs.

LP: #1629339

### CODE REVIEW

**Comment by kyrofa** [comment]
This PR is massive; I'm not confident we'll be able to give it a good review. Would you mind splitting it up? It definitely contains multiple features, perhaps one command per PR would be more prudent?

**Comment by kyrofa** [comment]
Note that the [contribution guide](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md) might be a good read.

**Comment by maxiberta** [comment]
Code is very similar between `snapcraft history` and `snapcraft status` (especially unit tests), so I thought they could be reviewed together. I tried to follow the contribution guidelines as much as possible; in particular, the 4 extra commits were pushed after the original PR was created, and I didn't want to alter the branch history.

**Comment by kyrofa** [comment]
I appreciate your following the guide in those respects, but this is multiple features. The guide specifically asks for one per PR, for reasons like this: reviewing a 1k-line PR takes a long time, and is never done as well as it could be. Just because the code is similar doesn't mean it makes for an easy review, and no one wants these features held up in review! Ideally such features would be built inside out (e.g. starting with the API and then focusing on the commands). This makes for logical break points between PRs, in good reviewable bite-sized chunks.

**Comment by maxiberta** [comment]
Closing as superseded by #844 and #845.

**Pull request closed without merging**
