### PR TITLE
Revert "qbs plugin: add plugin support for the Qt Build Suite (#1079)"

### PR DESCRIPTION
**Pull request by elopio**
This reverts commit 14873e9891ad5bcc10ccdf66f31b8f78e7e62600.

The qbs integration tests are failing in yakkety and zesty, in armhf. We need to first understand those errors and fix them before getting this plugin again in snapcraft.

### CODE REVIEW

**Comment by kyrofa** [comment]
Remember this will show in master's history along with the QBS merge. Mind making the commit mention WHY the reversion is happening?

**Comment by elopio** [comment]
This requires #1133.

**Comment by sergiusens** [comment]
I don't think that reverting is the right thing. Maybe update the tests instead.

**Comment by elopio** [comment]
@sergiusens update to expect a failure in arm?

**Comment by kyrofa** [comment]
I'm going to go ahead and merge this after discussion this morning. We can try again next release.

**Comment by jakepetroules** [comment]
And when you do re-add it, note that it is NOT called "Qt build suite" (anymore). Qbs is like DVD now. It doesn't stand for anything. It's just "Qbs".

[1] https://codereview.qt-project.org/#/c/161228/
[2] https://codereview.qt-project.org/#/c/161229/

**Comment by jhult** [comment]
@dpniel, @sergiusens, @elopio, @kyrofa, 

Any updates on getting this fixed/merged?

**Comment by bjorn** [comment]
Aaargh, I was so happy to see Qbs support in the changelog, until I found out it was later removed again. I'm quite desperate to drop qmake from my project and right now only need to maintain those files for the snap build. How hard would it be to reintroduce this plugin?

**Pull request merged**
