### PR TITLE
kde extension: new content snap for core20

### PR DESCRIPTION
**Pull request by jriddell**
- [X ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X ] Have you successfully run `./runtests.sh static`?
- [X ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
Thanks Jonathan, the run time test has failed

**Comment by MehdiChinoune** [comment]
`kde-frameworks-5-91-qt-5-15-3-core20{,-sdk}` is not available for aarch64!

**Comment by jriddell** [comment]
arm64 is a work in progress

**Comment by sergiusens** [comment]
is the content snap on stable? it is the only way it can be consumed as the default provider for the plug

    + '[' 'ERROR: not connected to the kde-frameworks-5-91-qt-5-15-3-core20 content interface.' = 'hello world' ']'

**Review by sergiusens — APPROVED** [review]

**Comment by MehdiChinoune** [comment]
> arm64 is a work in progress

3 months and no sign of arm64!

**Pull request merged**
