### PR TITLE
cli: allow snap-id for validate

### PR DESCRIPTION
**Pull request by sergiusens**
Info API can only retrieve snap-id's for what is publicly available,
workaround the issue by allowing for using the snap-id as a fallback
to the snap-name.

LP: #1902913

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by nessita** [comment]
Thank you Sergio for working on this!

I've reviewed the code and it looks good to me. I would just mention that I think there are no unit tests added for the newly added if branch, do you think that's something doable/worth it?

**Comment by sergiusens** [comment]
Thanks @nessita. That code path is tested through the test_validate case we have which leverages our fake store servers.

We have a long lasting tech debt to move this block of code closer to where the unit test lives, `_store.py` is scheduled to disappear.

**Review by cjp256 — APPROVED** [review]

**Comment by sergiusens** [comment]
In case you want to try this out:

    snap install snapcraft --classic --channel edge/pr-3349

Or refresh

    snap refresh snapcraft --channel edge/pr-3349

**Comment by nessita** [comment]
I've tested this and it's not working since the added variable `snap_id` is colliding with an already existing `snap_id`. I think the new one should be named `approved_snap_id` or similar.

**Comment by sergiusens** [comment]
that should be fixed and more thoroughly tested now

**Comment by nessita** [comment]
I can confirm this now works as expected.

**Review by cjp256 — APPROVED** [review]
LGTM

**Pull request merged**
