### PR TITLE
spread: improve resilience of lxd-type-base test

### PR DESCRIPTION
**Pull request by lengau**
This test often times out on `lxc stop` on Google runners.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----

#4236

### CODE REVIEW

**Review by sergiusens — APPROVED** [review]

**Comment by sergiusens** [comment]
can this go to hotfix/7.5 first?

**Comment by sergiusens** [comment]
nevermind, everything seems more funtional today

**Comment by sergiusens** [comment]
remember, no merge commits in main

**Comment by lengau** [comment]
@sergiusens oops, sorry - meant to squash.

**Pull request merged**
