### PR TITLE
Add process-dependency-links option to Python plugins

### PR DESCRIPTION
**Pull request by OddBloke**
This will run pip install with --process-dependency-links as per [0].

[0] https://pip.pypa.io/en/stable/reference/pip_wheel/#cmdoption--process-dependency-links

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Hi, thanks for your contribution. This looks good but seems to have failed and is missing unit tests

**Comment by OddBloke** [comment]
I've addressed the failing tests, and added more to cover my changes.

Unfortunately, the static check is failing; I'd appreciate thoughts on how to address that failure. (Or feel free to ignore it! ;)

**Comment by elopio** [comment]
Welcome @OddBloke !
The static error comes from the mccabe complexity check. When a function is too big it means it's clear anymore and needs to be split.
I would to see one function for installing pip, one function for installing the requirements and one for installing the python-packages. But there are many other possible refactors.

**Comment by sergiusens** [comment]
El 01/08/16 a las 23:59, Leo Arias escribió:
> Welcome @OddBloke <https://github.com/OddBloke> !
> The static error comes from the mccabe complexity check. When a function
> is too big it means it's clear anymore and needs to be split.
> I would to see one function for installing pip, one function for
> installing the requirements and one for installing the python-packages.
> But there are many other possible refactors.
>

I discussed this in real life already, sorry for not mentioning here. I will take care of the complexity issue.

**Comment by OddBloke** [comment]
There were merge conflicts, which I've just fixed up.

**Comment by SamYaple** [comment]
@OddBloke youll have to rebase on a patch that just merged, but if should clear up that complexity issue with a bit of wiggle room to add this option in (for at least python2).

I am working on unifying the python plugins as right now they duplicate alot of code

**Comment by OddBloke** [comment]
I've rebased but, unfortunately, I'm still seeing that complexity check fail.

**Comment by sergiusens** [comment]
Closing in favor of #734

**Pull request closed without merging**
