### PR TITLE
adding option to decompress tar.lzma cleanly

### PR DESCRIPTION
**Pull request by heesen3**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [ ] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
This is not aligned with the project goals. sources in snapcraft are not meant to be interacted with during runtime through a gui.

**Comment by elopio** [comment]
Hey @heesen3, python has a module to decompress lzma: https://docs.python.org/3/library/lzma.html

**Comment by heesen3** [comment]
actually i was trying to fix this bug

**Comment by kalikiana** [comment]
@heesen3 Which bug are you referring to? Is it [filed on Launchpad](https://bugs.launchpad.net/snapcraft)?

**Comment by heesen3** [comment]
https://bugs.launchpad.net/snapcraft/+bug/1567524

**Comment by elopio** [comment]
Yes @heesen3, but to fix that bug you can't open a dialog. This is a command-line tool, so you should fix it differently. Take a look at how the other sources are handled, and take a look at the python link I sent. If you get it working, make a new pull request. If you have problems, talk to us on IRC.

**Pull request closed without merging**
