### PR TITLE
Strip common path prefixes from linkname as well as name when extracting a tarfile

### PR DESCRIPTION
**Pull request by mhall119**
Stripping common path prefixes from the member name breaks hardlink name resolution unless you perform the same operation on the member linknames

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
@mhall119 according to the integration tests, this seems to bust the nodejs and rust plugins.

**Comment by kyrofa** [comment]
ok to test

**Pull request merged**
