### PR TITLE
lxd: Don't assume user ID to 1000 for raw.idmap

### PR DESCRIPTION
**Pull request by kalikiana**
Fixes: [bug 1700703](https://bugs.launchpad.net/snapcraft/+bug/1700703)

### CODE REVIEW

**Comment by elopio** [comment]
@kalikiana I took your branch, but this still fails for me. Do I have to do something special for this? Could you reproduce my error and did this work for you?
Here is my error: http://paste.ubuntu.com/24978212/

**Comment by kalikiana** [comment]
This branch is fixing the UID mapping issue I saw in your logs, your new paste seems to confirm that it worked since the error is gone.

I don't know what your "Failed to run lxc.hook.pre-start" is about, I see no meaningful error message anymore... can you paste /var/log/lxd/snapcraft-my-snap-name/lxc.conf?
If snapcraft-my-snap-name exists,, can you "lxc delete --force snapcraft-my-snap-name" and try again?

**Comment by elopio** [comment]
Here is the .conf file: http://paste.ubuntu.com/24984714/

**Comment by sergiusens** [comment]
this is what I get on DO http://pastebin.ubuntu.com/25011429/

**Comment by sergiusens** [comment]
That is using lxd from the archives on xenial fwiw

**Pull request merged**
