### PR TITLE
replace : with _ in file names

### PR DESCRIPTION
**Pull request by andyli**
It's done such that we can clone the repo in WSL (Bash on Ubuntu on Windows) correctly.

---

Checklist:

- Have you signed the contributor licence agreement?
  https://www.ubuntu.com/legal/contributors

Yes.

- Is there a reported a bug for the problem you are fixing?
  https://bugs.launchpad.net/snapcraft/
  If there is none, please report it. Once you have the BUG_NUMBER,
  replace it here:

LP: [#1683986](https://bugs.launchpad.net/snapcraft/+bug/1683986)

- Have you read our contribution guide?
  [CONTRIBUTING.md](CONTRIBUTING.md)

Yes.

### CODE REVIEW

**Comment by jocave** [comment]
@sergiusens I see no problem with the changes proposed here.

The reason the paths were created as they were is simply because that is the default when invoking the "startprovider" tool in plainbox: http://checkbox.readthedocs.io/en/latest/tutorials.html#creating-an-empty-provider

There is no particular convention that says the directory must keep this name.

@andyli thanks for the patch!

**Comment by elopio** [comment]
Thanks a lot for the contribution @andyli. If you need something else to test on windows, let us know!

@jocave's +1 is enough here. I'll trigger the autopkgtests to confirm that the demo is still working.

**Comment by andyli** [comment]
bump ;)

**Comment by elopio** [comment]
Hey @andyli. We are finishing the [snapcraft 2.29 release](https://forum.snapcraft.io/t/in-progress-snapcraft-2-29/346). We will resume landing soon, sorry for the delay.

**Comment by andyli** [comment]
Ah, okay. Just want to make sure it is not forgotten. Thanks!

**Pull request merged**
