### PR TITLE
Go: unable to build snap when using `go mod` and main package is not in the root

### PR DESCRIPTION
**Pull request by pavel-d**
When using go modules, `go build -o <path>` will pick up main package only if it's in the root of repository.

Steps to reproduce:

0. Given a go module, where [main](https://github.com/pavel-d/snaptest/blob/master/cli/main.go) package is located in `./cli` subdirectory
1. Clone https://github.com/pavel-d/snaptest
2. `cd snaptest`
2. Run `snapcraft build --use-lxd --debug`

Result:
```
snapcraft --use-lxd  --debug
The LXD provider is offered as a technology preview for early adopters.
The command line interface, container names or lifecycle handling may change in upcoming releases.
Launching a container.
Waiting for container to be ready
......................
status: done
snapd 2.43.3 from Canonical✓ refreshed
Skipping pull snaptest (already ran)
Building snaptest 
go build -o /root/parts/snaptest/install/bin
go build: no main packages to build
Failed to run 'go build -o /root/parts/snaptest/install/bin' for 'snaptest': Exited with code 1.
Verify that the part is using the correct parameters and try again.
snapcraft-snaptest # snapcraft --version
snapcraft, version 3.10.1
```

The `./...` pattern matches all the packages within the current module and `go build` will automatically build main packages in subdirectories.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by cjp256** [comment]
A couple of unit tests need to be updated:
https://travis-ci.org/snapcore/snapcraft/jobs/659245540#L7921

**Comment by sergiusens** [comment]
This is great, an integration test would be really good though, it can look exactly like the current go mod one but with a main package in a subdir. I can add it to this PR if you cannot do so.

**Comment by pavel-d** [comment]
@sergiusens, thanks, I've added an integration test. 

Unfortunately, I haven't figured out how to run it locally, I hope I did it correctly :)

**Comment by cjp256** [comment]
Nice! 

@pavel-d: If you have lxd installed, you can test it with:

```
# From inside snapcraft directory, build snapcraft snap to use for testing.
snapcraft snap

# Run spread test locally using LXD.
./runtests.sh spread lxd:tests/spread/plugins/go/run-go-mod-subdir
```

I am running it now myself...

**Comment by cjp256** [comment]
Unfortunately the CLA check is failing because one (or more) of the commits were made with `@assembla.com` address instead of the `@travis-ci.com` which is associated with the CLA.

**Comment by pavel-d** [comment]
@cjp256, oh, thanks. I've fixed my email address in commits.

**Pull request merged**
