### PR TITLE
docs: import Sphinx scaffolding for documentation work

### PR DESCRIPTION
**Pull request by dboddie**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----

### CODE REVIEW

**Comment by lengau** [comment]
Please include the tox configuration here too. It's line 113 to the end of tox.ini in the starbase file: https://github.com/canonical/starbase/blob/main/tox.ini#L113

**Review by lengau — APPROVED** [review]

**Review by lengau — APPROVED** [review]
I've rebased this on main, which should fix the linting issue. Once the tests have succeeded I'm happy with this.

**Comment by sergiusens** [comment]
Seems we need to add python-apt into the docs target
```
  ERROR: Could not find a version that satisfies the requirement python-apt (from versions: 0.0.0, 0.7.8)
```

**Review by lengau — APPROVED** [review]

**Comment by lengau** [comment]
The spread test failure should be fixed once #4102 is merged.

**Pull request merged**
