### PR TITLE
Pass --work-dir param for out-of-tree builds

### PR DESCRIPTION
**Pull request by abitrolly**
https://forum.snapcraft.io/t/out-of-tree-builds-with-snapcraft/9830

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by abitrolly** [comment]
Testing it with `snapcraft-pr.init 2463` and `snapcraft-pr.init 2463 build`.

**Comment by abitrolly** [comment]
This sucessfully starts the build process:

    snapcraft-pr 2463 --work-dir ~/xxx

At the end it fails with linker error as described in https://github.com/snapcore/core18/issues/86 because I am building C code for `core18` on Ubuntu 18.10.

**Comment by abitrolly** [comment]
@sergiusens it is ready for review. I won't be able to write test for this. It required passing it to `build` step and checking directory is created and filled in `prime`, and original directory is clean.

There is also an issue with `pack` step. I want `.snap` to be created in `--work-dir` be default. Otherwise this step fails the build if project checkout is read only.

**Comment by sergiusens** [comment]
Considering that no test will be added, report a bug on https://launchpad.net/snapcraft

Considering that, I will close this. If you plan to work on it though, feel free to open.

**Pull request closed without merging**
