### PR TITLE
Add an option for setting npm flags option

### PR DESCRIPTION
**Pull request by guilhem**
This is useful when I faced this problem https://github.com/npm/npm/issues/18287 (sadly not only on windows) on this project: https://github.com/webpro/reveal-md
I had to add `--no-optional` flag to work.

### CODE REVIEW

**Comment by sergiusens** [comment]
Hi there, thanks for this!
I suppose this could be solving [LP: #1742559](https://bugs.launchpad.net/snapcraft/+bug/1742559)

Mind updating the unit tests? Or do you want us to take it from here?

**Comment by guilhem** [comment]
thank you @sergiusens 
I added option to yarn, but yes I'm not really familiar with python unittest, you can do whatever you want with my branch/PR :)

**Comment by kyrofa** [comment]
Alright @guilhem, I'll take it from here. Thank you!

**Comment by kalikiana** [comment]
This seems to fix [LP: #1742559](https://bugs.launchpad.net/snapcraft/+bug/1742559)?

**Pull request merged**
