### PR TITLE
extensions: make GNOME 3.38 stable

### PR DESCRIPTION
**Pull request by sergiusens**
- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Review by cjp256 — COMMENTED** [review]
Unrelated godep test failures.

**Review by cjp256 — APPROVED** [review]

**Comment by kenvandine** [comment]
I think this is ready to land now, thanks!

**Comment by sergiusens** [comment]
Ken VanDine <notifications@github.com> writes:

> I think this is ready to land now, thanks!
>

I believe we should make the bindtext2domain fix first before 
doing this.

**Comment by kenvandine** [comment]
Any update on this?  @sergiusens

**Review by cmatsuoka — APPROVED** [review]

**Comment by sergiusens** [comment]
Ignoring the publishing failure

**Pull request merged**
