### PR TITLE
Add setuptools tests_require.

### PR DESCRIPTION
**Pull request by squidsoup**

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by squidsoup** [comment]
Were this launchpad, I probably would have made josepht:add_depends a prerequisite branch.

**Comment by elopio** [comment]
ok to test

**Comment by sergiusens** [comment]
Thanks, but closing this in favor of #550

**Pull request closed without merging**
