### PR TITLE
Fix python2 compile cache removal

### PR DESCRIPTION
**Pull request by SamYaple**
\_\_pycache\_\_ is python3. python2 generates .pyc files in the folders
next to the origin .py file.

There is a python3.5 related \_\_pycache\_\_ directory that is excluded
as well.

LP:#1603200

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by sergiusens** [comment]
Thanks for the fix!

**Pull request merged**
