### PR TITLE
extensions: Do not default to Nvidia VDPAU

### PR DESCRIPTION
**Pull request by nteodosio**
In a hybrid Intel + Nvidia setup, it is costumary to use Intel-Vaapi for
hardware acceleration instead of Nvidia-Vdpau (unless the user chooses
otherwise); this avoids unecessary power consumption.

Moreover, for software that don't work with Vdpau yet, the previous changes
would hard lock to Vdpau nonetheless (e.g. Chromium [LP: #1816497](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1816497)), resulting
in no hardware acceleration where Vaapi is available.

- [X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
  ```
  snapcraft/projects.py:320: error: Unexpected keyword argument "extra" for "__init_subclass__" of "object"
  snapcraft/projects.py:639: error: Unexpected keyword argument "extra" for "__init_subclass__" of "object"
  Found 2 errors in 1 file (checked 153 source files)
  make: *** [Makefile:29: test-mypy] Error 1
  ```
- [ ] Have you successfully run `pytest tests/unit`?
  ```
  ImportError while loading conftest '/home/nteodosio/canonical/snaps/snapcraft/tests/conftest.py'.
  tests/conftest.py:22: in <module>
      from craft_store.auth import MemoryKeyring
  E   ModuleNotFoundError: No module named 'craft_store'
  ```

### CODE REVIEW

**Comment by nteodosio** [comment]
It seems the failed test was network issue, can it be triggered again?

Also, I should have linked to [Nvidia: PRIME Render Offload](https://download.nvidia.com/XFree86/Linux-x86_64/510.54/README/primerenderoffload.html):

> To configure a graphics application to be offloaded to the NVIDIA GPU screen, set the environment variable __NV_PRIME_RENDER_OFFLOAD to 1.

Please note this is holding back hardware accelerated video decoding on (at least) Chromium snap currently.

**Comment by sergiusens** [comment]
since this is urgent, I am retargetting to our release branch, but mind dropping the extra commit?
Also, a review from someone like @oSoMoN or @kenvandine would help

**Comment by sergiusens** [comment]
Is this already part of the new loader code base on https://github.com/snapcore/snapcraft-desktop-integration ?

**Comment by sergio-costas** [comment]
@nteodosio There is an extra commit in this MR; I think that you have to rebase your branch from snapcore:release/7.1.

About the patch itself, where is set "__NV_PRIME_RENDER_OFFLOAD"?

**Comment by oSoMoN** [comment]
> where is set "__NV_PRIME_RENDER_OFFLOAD"?

IIUC, this has to be set by the user if they want to force the use of the NVIDIA GPU.

**Comment by oSoMoN** [comment]
Can you add a comment that links to https://download.nvidia.com/XFree86/Linux-x86_64/510.54/README/primerenderoffload.html#configureapplications ?

**Comment by sergio-costas** [comment]
> > where is set "__NV_PRIME_RENDER_OFFLOAD"?
> 
> IIUC, this has to be set by the user if they want to force the use of the NVIDIA GPU.

Yes, I get that. The point is: does that extend inside the container? I mean: if I set __NV_PRIME_RENDER_OFFLOAD to 1 in my bash.rc, does it always be set inside the container too?

**Comment by oSoMoN** [comment]
> does that extend inside the container?

Yes it does. You can easily test it with e.g.:

    $ env __NV_PRIME_RENDER_OFFLOAD=1 snap run --shell chromium
    $ env | grep PRIME

**Comment by nteodosio** [comment]
Thank you for the quick responses and review!

> Is this already part of the new loader code base on https://github.com/snapcore/snapcraft-desktop-integration ?

No, I didn't know of that. I suppose I should submit it there too?

**Review by sergio-costas — APPROVED** [review]
Looks good to me.

**Comment by sergio-costas** [comment]
@oSoMoN @sergiusens I don't have write permission, so my review doesn't count for github...

**Review by oSoMoN — APPROVED** [review]
LGTM, thanks!

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
