### PR TITLE
elf: set no-default-lib for all elf files if patching

### PR DESCRIPTION
**Pull request by sergiusens**
Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
Closes: #1665

**Comment by kyrofa** [comment]
Hmm... something is broken here. git-ubuntu can't find libpthread, libdl, libc, nothing. Pretty much anything supplied by the core snap. rpaths seem completely empty:

```
$ patchelf --print-rpath prime/usr/bin/python3

$
```

**Comment by sergiusens** [comment]
@kyrofa different story for me, although I did this run as launchpad buildd's would (`snapcraft pull` first then `snapcraft`).

```
ubuntu@snapcraft-xenial-dev:~/usd-importer$ patchelf --print-rpath prime/usr/bin/python3
/snap/core/current/lib/x86_64-linux-gnu
ubuntu@snapcraft-xenial-dev:~/usd-importer$ patchelf --print-interpreter prime/usr/bin/python3
/snap/core/current/lib64/ld-linux-x86-64.so.2
ubuntu@snapcraft-xenial-dev:~/usd-importer$ $(patchelf --print-interpreter prime/usr/bin/python3) --list prime/usr/bin/python3
        linux-vdso.so.1 =>  (0x00007ffd2dbec000)
        libpthread.so.0 => /snap/core/current/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe36c30b000)
        libdl.so.2 => /snap/core/current/lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe36c107000)
        libutil.so.1 => /snap/core/current/lib/x86_64-linux-gnu/libutil.so.1 (0x00007fe36bf04000)
        libm.so.6 => /snap/core/current/lib/x86_64-linux-gnu/libm.so.6 (0x00007fe36bbfb000)
        libc.so.6 => /snap/core/current/lib/x86_64-linux-gnu/libc.so.6 (0x00007fe36b831000)
        /snap/core/current/lib64/ld-linux-x86-64.so.2 (0x00007fe36c528000)
ubuntu@snapcraft-xenial-dev:~/usd-importer$ patchelf --print-rpath prime/usr/bin/python
/snap/core/current/lib/x86_64-linux-gnu
ubuntu@snapcraft-xenial-dev:~/usd-importer$ patchelf --print-interpreter prime/usr/bin/python
/snap/core/current/lib64/ld-linux-x86-64.so.2
ubuntu@snapcraft-xenial-dev:~/usd-importer$ $(patchelf --print-interpreter prime/usr/bin/python) --list prime/usr/bin/python
        linux-vdso.so.1 =>  (0x00007fff3439a000)
        libpthread.so.0 => /snap/core/current/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4bb45bc000)
        libdl.so.2 => /snap/core/current/lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4bb43b8000)
        libutil.so.1 => /snap/core/current/lib/x86_64-linux-gnu/libutil.so.1 (0x00007f4bb41b5000)
        libm.so.6 => /snap/core/current/lib/x86_64-linux-gnu/libm.so.6 (0x00007f4bb3eac000)
        libc.so.6 => /snap/core/current/lib/x86_64-linux-gnu/libc.so.6 (0x00007f4bb3ae2000)
        /snap/core/current/lib64/ld-linux-x86-64.so.2 (0x00007f4bb47d9000)
```

**Comment by sergiusens** [comment]
@kyrofa I have good news and bad news; everything builds fine with this branch, but I think `git-ubuntu` is affected by the library finding logic the same was so let's merge this in 2 weeks and discuss it over with nacc

**Comment by kyrofa** [comment]
@sergiusens sounds good to me.

**Pull request closed without merging**
