### PR TITLE
project_loader: replace dict keys as well as values

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

The snapcraft CLI actually runs a text replacement over the `snapcraft.yaml`, replacing all occurrences of its built-in variables (such as `$SNAPCRAFT_STAGE`) with their actual values, knowing that, once these are migrated into the final `snap.yaml` the variables have no meaning. However, when it comes to running the replacements on dicts, it only checks the values for replacement, not the keys. This PR fixes [LP: #1746636](https://bugs.launchpad.net/snapcraft/+bug/1746636) by simply running replacements on the keys as well as the values.

### CODE REVIEW

**Comment by kubiko** [comment]
I can confirm this is fixing bug [LP: #1778287](https://bugs.launchpad.net/snapcraft/+bug/1778287)

**Comment by sergiusens** [comment]
This should also fix the organize bug, https://bugs.launchpad.net/snapcraft/+bug/1746636, so I am marking LP: #1778287 as a dup of that one.

**Comment by kyrofa** [comment]
> [...] for which we already had a bug

Good catch @sergiusens, forgot about that one. I've fixed the commit as well as the PR description.

**Comment by diddledan** [comment]
Two potentially related bugs that would be good to get squished at the same time: [LP#1746633](https://bugs.launchpad.net/snapcraft/+bug/1746633) and [LP#1766878](https://bugs.launchpad.net/snapcraft/+bug/1766878)

**Pull request merged**
