### PR TITLE
repo: implement :target suffix for package names

### PR DESCRIPTION
**Pull request by kalikiana**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----
Fixes: #1502

### CODE REVIEW

**Comment by kyrofa** [comment]
(tests are failing)

**Comment by kalikiana** [comment]
No they're not. This is `ERROR: test_build_maven_plugin (test_maven_plugin.MavenPluginTestCase)
test_maven_plugin.MavenPluginTestCase.test_build_maven_plugin
BlockingIOError: [Errno 11] write could not complete without blocking`. I'll restart the job again.

**Comment by kalikiana** [comment]
Once more.

**Comment by kalikiana** [comment]
Latest error output is this `E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-arm64/Packages  404  Not Found [IP: 91.189.88.152 80]` so somehow the default sources are broken? I don't know how to test this... will close for now and discuss other options.

**Comment by lool** [comment]
(Is this the best place to discuss implementation?)

Just wanted to say that :target is nice and useful, but:
1) it would make sense to default to :target for stage-packages (and to build architecture for build-packages)
2) hence it might make sense to offer :build and or :host architectures as well

**Pull request closed without merging**
