### PR TITLE
Fix trivial typo in warning for Go plugin (bug 1590245)

### PR DESCRIPTION
**Pull request by tsimonq2**
This fixes the typo detailed in [bug 1590245](https://bugs.launchpad.net/snapcraft/+bug/1590245).

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Thank @tsimonq2 

Mind clicking on "Update branch"?

**Comment by tsimonq2** [comment]
@sergiusens done

**Comment by elopio** [comment]
:+1:

**Pull request merged**
