### PR TITLE
integration tests: use ruby v2.4.2

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

Anything earlier fails to build with GCC7 on Artful.

### CODE REVIEW

**Comment by elopio** [comment]
Thanks @kyrofa. The travis test failed to download lxd, maybe because of the canonical maintenance. I've restarted the jobs.

The default `ruby-version` on the plugin is `2.4.0`. Wouldn't it be better to remove it from all the integration tests, and update only the default?

**Comment by sergiusens** [comment]
How about just piggybacking on #1645 and making it just work through that?

**Comment by sergiusens** [comment]
Actually, that should be the path.

**Comment by kyrofa** [comment]
Yeah that's fine as well. I'll propose removing the version from these instead, and we can land both.

**Pull request closed without merging**
