### PR TITLE
Remove the debian packaging

### PR DESCRIPTION
**Pull request by elopio**
It was moved to the debian branch:
https://github.com/snapcore/snapcraft/tree/debian

LP: #1628609

### CODE REVIEW

**Comment by martinpitt** [comment]
Wrt. the autopkgtest failure:
```W: The repository 'http://ppa.launchpad.net/elopio/snapcraft-semaphore/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/elopio/snapcraft-semaphore/ubuntu/dists/xenial/main/source/Sources  404  Not Found
```
Upload or copy any package to that PPA to the xenial series and let LP publish it, to force generation of package indexes for xenial. You can remove the package again then.

**Comment by sergiusens** [comment]
I am in crux with this, after discussing a bit with @martinpitt during a f2f conversation I feel inclined to keep the `debian` packaging in `master` for now as it will endure some more burden during release time.

**Comment by elopio** [comment]
what? Well, I don't really mind. Should I delete the snapcore/snapcraft/debian branch?

**Comment by sergiusens** [comment]
El 04/11/16 a las 17:09, Leo Arias escribió:
>
> what? Well, I don't really mind. Should I delete the 
> snapcore/snapcraft/debian branch?
>

Keep it for now, we might need to revisit this in the future.

**Pull request closed without merging**
