### PR TITLE
Updating styling and examples for `snapcraft init` in lifecycle.py

### PR DESCRIPTION
**Pull request by wandrewkeech**
This patch updates the indenting and extends the example properties included in the default boiler-plate produced by `snapcraft init`

Bug submitted on Launchpad, #1604504
https://bugs.launchpad.net/snapcraft/+bug/1604504

### CODE REVIEW

**Comment by kyrofa** [comment]
@wandrewkeech thanks for the PR! You're missing just a few things here:

1. Please make sure a bug exists for this task and make sure you reference it in your commit.
2. Please sign the contributor license agreement.

Please see the [contribution guide](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md) for more information.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by wandrewkeech** [comment]
Sorry for the messy history, I couldn't solve it. Original PR commit message ammended, and CLA signed (was confused with the Ubuntu membership with Launchpad as being the same thing).

**Comment by wandrewkeech** [comment]
Closing this to quickly redo it and get rid of all this grossness.

**Pull request closed without merging**
