### PR TITLE
add stage/usr/local/lib to cmake library path

### PR DESCRIPTION
**Pull request by diddledan**
Some libraries may be installed in `<stage>/usr/local/lib{,/x86_64-linux-gnu}` which cannot be found by cmake builds.

- Add `<stage>/usr/local/lib` and `<stage>/usr/local/lib/x86_64-linux-gnu` to `CMAKE_LIBRARY_PATH` environment variable in cmake pluign

Possibly related to https://bugs.launchpad.net/snapcraft/+bug/1637946 in that the failure I'm fixing with this change is similar to the failure in that bug which @sergiusens suggests will be fixed by a different method. My fix here is more targeted on libraries in /usr/local ONLY, and won't fix the bug above completely.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [ ] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by kyrofa** [comment]
@diddledan your tests are failing here, please take a look.

**Comment by diddledan** [comment]
Sorry, yes, I saw that they were failing but haven't had the time to get back to fix them :-) I'm working on it now...

**Comment by diddledan** [comment]
I fixed the specific tests related to my changes. I do not know what the integration test which failed subsequently is attempting to do or why it failed.

**Comment by sergiusens** [comment]
Sorry for taking so long, but mind updating the PR?

**Comment by kalikiana** [comment]
For the record (false negative):

    Collecting mccabe==0.6.1 (from -r requirements-devel.txt (line 6)) [...]
    TypeError: getresponse() got an unexpected keyword argument 'buffering' [...]
      File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
        total -= 1
    TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by sergiusens** [comment]
Do we still need this one?

**Pull request closed without merging**
