### PR TITLE
remote-build: add clean flag

### PR DESCRIPTION
**Pull request by cjp256**
...and cleanup git repository at build completion while we're here.

### CODE REVIEW

**Comment by sergiusens** [comment]
Hold any updates or travis retries to this until after we tag 3.9

**Comment by cjp256** [comment]
Rebased.

**Comment by cjp256** [comment]
added initial unit tests for remote-build, should be good to go now

**Comment by sergiusens** [comment]
Can you split these commits? Willing to merge the tests but not the clean functionality

**Comment by cjp256** [comment]
> Can you split these commits? Willing to merge the tests but not the clean functionality

Done. https://github.com/snapcore/snapcraft/pull/2785

Is it because you prefer the work we discussed to integrate with the `clean` command when using --provider=launchpad?  Or something else?  I can close this PR, I just found it useful to provide cleanup support in the mean-time.

**Comment by cjp256** [comment]
Per discussion with @sergiusens, will close pending future work to integrate with `clean` command and https://github.com/snapcore/snapcraft/pull/2678

**Pull request closed without merging**
