### PR TITLE
fix checker errors to let runtests.sh pass again

### PR DESCRIPTION
**Pull request by cpaelzer**
Fix indention errors that get the code checkers upset (LP: #1611402).

Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
The current checks are not broken but that could be related to the version of flake8 we use. Thanks!

Ideally a bug should be assigned to this task (as mentioned in CONTRIBUTING.md) for traceability reasons, given the size and impact of change it shouldn't be needed.

**Comment by sergiusens** [comment]
sorry, I failed to see you did the right thing wrt bug creation!

**Pull request merged**
