### PR TITLE
core18: removal

### LINKED ISSUE #4165: Remove core18 from Snapcraft
### What needs to get done

Snapcraft needs to drop core18 for the upcoming Snapcraft release

### Why it needs to get done

core18 has entered ESM, this is the same procedure that was done for core (aka core16)

### PR DESCRIPTION
**Pull request by sergiusens**
- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----
Fixes #4165

### CODE REVIEW

**Comment by sergiusens** [comment]
first pass, only production code and unit tests; missing spread and legacy integration tests

**Comment by sergiusens** [comment]
@ScarlettGatelyMoore or @jriddell is the neon stuff fore core20 gone since today?

```
error: cannot perform the following tasks:
- Ensure prerequisites for "neon-hello" are available (cannot install prerequisite "kde-frameworks-5-99-qt-5-15-7-core20": no snap revision available as specified)
```
?

**Comment by sergiusens** [comment]
@cmatsuoka @mr-cal this should be good to go, the kde spread test is also failing on other PRs

**Review by cmatsuoka — APPROVED** [review]
That was an extensive cleanup. Lots of code removed, but the result looks correct. Great work!

**Comment by ScarlettGatelyMoore** [comment]
> @ScarlettGatelyMoore or @jriddell is the neon stuff fore core20 gone since today?
> 
> ```
> error: cannot perform the following tasks:
> - Ensure prerequisites for "neon-hello" are available (cannot install prerequisite "kde-frameworks-5-99-qt-5-15-7-core20": no snap revision available as specified)
> ```
> 
> ?

I have added back the core20 content pack. Tests should pass. I will go through and remove the tests prior to my next cleanup. Sorry for the noise.

**Review by mr-cal — APPROVED** [review]

**Pull request merged**
