### PR TITLE
tests: run integration tests on trusty

### PR DESCRIPTION
**Pull request by elopio**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by elopio** [comment]
@sergiusens you said to add catkin, but catkin tests skip on anything that's not xenial. Can you please confirm the list of suites to add here?

**Comment by sergiusens** [comment]
@elopio let's do `general` and `store`

**Comment by kyrofa** [comment]
> catkin tests skip on anything that's not xenial

Would love to actually do a Catkin one, that's a pretty important Trusty target. We can add one that doesn't skip.

**Comment by elopio** [comment]
uhhh, problem!:
E: Unable to locate package squashfuse

**Comment by kyrofa** [comment]
@sergiusens is there a reason to run trusty tests in lxc instead of just on the Travis runner itself? It doesn't need squashfuse.

**Comment by sergiusens** [comment]
Yes, using containers will not work https://bugs.launchpad.net/snappy/+bug/1628289/comments/18

**Pull request closed without merging**
