### PR TITLE
snapcraft: fix or ignore PEP8 static errors

### PR DESCRIPTION
**Pull request by 3v1n0**
I was annoyed by these warnings... 

LP: [#1659816](https://bugs.launchpad.net/snapcraft/+bug/1659816)

### CODE REVIEW

**Comment by sergiusens** [comment]
aren't you using the pinned versions in requirements-devel.txt?

**Comment by 3v1n0** [comment]
Oh, maybe not?

Anyway, are these changes wrong with those versions too?

**Comment by kyrofa** [comment]
> Oh, maybe not... I preferred only use archive stuff

Me too, but I don't think the fix is to ignore stuff, because then even more recent versions of the tools won't check them.

**Comment by elopio** [comment]
what's C901?

**Comment by 3v1n0** [comment]
> what's C901?

```
snapcraft/internal/sources/__init__.py:150:1: C901 '_get_source_type_from_uri' is too complex (11)
snapcraft/tests/fake_servers.py:336:1: C901 'FakeStoreAPIRequestHandler.do_POST' is too complex (11)```

> Me too, but I don't think the fix is to ignore stuff, because then even more recent versions of the tools won't check them.

I'm only ignoring the too-complex error as above, not anything else... I fixed the syntax of other lines ignoring stuff (that was not using two leading spaces)

**Comment by elopio** [comment]
I think that a function with complexity 11 should be split in two functions. Ideally, more than that. I wonder why that is not caught by travis...

**Comment by 3v1n0** [comment]
@elopio if you check those functions, splitting them would cause their complexity to grow IMHO (unless we don't use maps or something).

That rule is fine, but it doesn't apply to all the cases.

**Comment by elopio** [comment]
@3v1n0 I think I would like to see a map for the source types. But not a big deal, +1 from me.

**Comment by sergiusens** [comment]
@3v1n0 we don't do static tests as part of the archive integration. We only rely on pypi and the reason is, we want to support the same codebase for xenial, yakkety and zesty.

**Comment by sergiusens** [comment]
oh, and we locked it to xenial's versions for people developing using the archive packages instead of pypi

**Comment by kyrofa** [comment]
> I'm only ignoring the too-complex error as above

Right, that's what I'm talking about. Ignoring it means that the function can further grow in complexity, and even the newer review tools will never catch it. I'd rather live with the static error, or split it.

**Comment by 3v1n0** [comment]
Ok, fine... You want me to remove the `# noqa: C901` and leave the rest or just ignoring all this?

**Comment by sergiusens** [comment]
I'll leave that call to @elopio, but if this goes in please update `requirements-devel.txt` with the appropriate static checker versions

**Comment by elopio** [comment]
I said I'm ok with this. The branch makes the code a little better, and then if somebody comes with a clever way to simplify the function while keeping it clear and simple, we can remove the #noqa. Also I don't think we are at risk of filling our repo with noqa, this are two special cases.

The one that's getting pretty ugly is the fake server. I can take an action to make it better after this sprint.

**Pull request merged**
