### PR TITLE
Also use INSTALLROOT for make plugin.

### PR DESCRIPTION
**Pull request by jhobbs**
Some projects don't use DESTDIR - it's only a gnu convention.  make will ignore arguments that aren't used, so appending is cleaner than exposing a new option on the command line, and just works.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by jhobbs** [comment]
What do I do now? I can't access the autopkgtest results. I didn't make any changes that would have broken packaging...

**Comment by kyrofa** [comment]
retest this please

**Comment by kyrofa** [comment]
ok to test

**Comment by jhobbs** [comment]
ok!

**Comment by sergiusens** [comment]
Should we piggy back every other option or implement something like this https://bugs.launchpad.net/snapcraft/+bug/1609116 ?

**Comment by sergiusens** [comment]
I am closing this one in favor of #711 which will handle more cases. Please reopen if you think it is a mistake.

**Pull request closed without merging**
