### PR TITLE
Shout -> Lounge, the official fork

### PR DESCRIPTION
**Pull request by MaxLeiter**
Updated the shout snap to point to Lounge
LP: [#1659471](https://bugs.launchpad.net/snapcraft/+bug/1659471)

### CODE REVIEW

**Comment by MaxLeiter** [comment]
The travis test is failing on 2.7 because it can't verify I signed the CLA - I did, but it never asked my github. See the bug report

**Comment by sergiusens** [comment]
Hey there, question, is `shout` abbandoned or would you rather have lounge as the the demo? Last I heard the upstream for shout wanted complete control so lounge was created. Ideally I would try and get a snapcraft.yaml into the lounge repo and have it push automatically to the edge channel instead.

What do you think?

**Comment by MaxLeiter** [comment]
Depends on your definition of abandoned - the creator wanted to leave Shout as his pet project but allowed us to fork for more active development. He points people to us on IRC if people ask about Shout

I think a package specific build file in Lounge repo wouldn't be too great, to this point we've been making separate repos for different distributions

**Comment by sergiusens** [comment]
Where did you sign the CLA? Did you follow the instructions in the CONTRIBUITIONS.md file?

**Comment by sergiusens** [comment]
Just ran it again

```
Checking the licence agreement for mleiter18@priorypanther.com...
echo $email | cut -d @ -f 2
Logging into Launchpad...
Checking for a Launchpad account associated with this email address...
The contributor does not have a Launchpad account.
Cannot confirm that the contributor has signed the agreement.
```

**Comment by MaxLeiter** [comment]
My launchpad account is using a different email; I just added my current email so hopefully that'll work.

**Comment by sergiusens** [comment]
```
Checking the licence agreement for mleiter18@priorypanther.com...

echo $email | cut -d @ -f 2

Logging into Launchpad...

Checking for a Launchpad account associated with this email address...

Contributor: https://api.launchpad.net/1.0/~giraffestock

Checking if the contributor has signed the CLA...

The contributor has a Launchpad account, but has not signed the CLA.

Cannot confirm that the contributor has signed the agreement.
```

There's also a conflict now

**Comment by sergiusens** [comment]
Please reopen if you wish to push this further. I am closing for now due to inactivity. Sorry

**Pull request closed without merging**
