### PR TITLE
Add https_proxy support to maven plugin.

### PR DESCRIPTION
**Pull request by squidsoup**
No https_proxy configuration is written to the maven configuration file.

Snaps using the maven plugin which fetch dependencies over https can't currently be built on launchpad. Ideally I would like to test this change against a ppa on launchpad's test build infrastructure before this is considered for merging. 

lpbug: https://bugs.launchpad.net/snapcraft/+bug/1592218

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Looks good, you just reminded me how hard it was to get proxy support with maven :-P

Have you tried this on launchpad builders yet?

**Comment by squidsoup** [comment]
Still awaiting a test, discovered that the snap proxy is currently blocking our staging PPAs, which prevents me from testing my build of snapcraft with this patch. Will keep you updated!

**Comment by elopio** [comment]
Hey Kit, it's great to see you here! :)

**Comment by squidsoup** [comment]
Just a brief update on this, LP snap proxies are now able to see staging PPAs, however the problem is persisting despite this patch and requires further investigation. Will hopefully know more soon, thanks.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by squidsoup** [comment]
Superseded by https://github.com/snapcore/snapcraft/pull/642

**Pull request closed without merging**
