### PR TITLE
ros: remove generator warnings from linter spread tests

### PR DESCRIPTION
**Pull request by cmatsuoka**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----

### CODE REVIEW

**Comment by artivis** [comment]
Actually not sure what's going on here (with respect to https://github.com/snapcore/snapcraft/pull/4184). Friendly ping @Guillaumebeuzeboc .

**Comment by Guillaumebeuzeboc** [comment]
> Actually not sure what's going on here (with respect to #4184). Friendly ping @Guillaumebeuzeboc .

Was the linter updated?

**Comment by cmatsuoka** [comment]
The linter was not changed AFAIK (but @mr-cal can confirm this), any recent changes in the ROS libraries?

**Comment by mr-cal** [comment]
> The linter was not changed AFAIK (but @mr-cal can confirm this), any recent changes in the ROS libraries?

No changes to our linters, so a change to the ROS library or its dependencies is the likely cause.


P.S. - this is the

**Review by mr-cal — APPROVED** [review]
P.S. - This is the 3rd time this has failed ([1](https://github.com/snapcore/snapcraft/pull/4113) and [2](https://github.com/snapcore/snapcraft/pull/4184)).  At some point, we should consider a less hard-coded way to test this.

**Pull request merged**
