### PR TITLE
fix yarn version url

### PR DESCRIPTION
**Pull request by fkromer**
In case the yarn version is specified in snapcraft.yaml with
nodejs-yarn-version previously to this fix it was not possible
to create a snap:

Network request error: 404 Client Error: Not Found for url: https://github.com/yarnpkg/yarn/releases/download/1.22.4/yarn-1.22.4.tar.gz

Correct urls are like e.g.
https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz

- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by cjp256** [comment]
Well that certainly checks out with the comment right next to it :)

**Comment by fkromer** [comment]
Sorry, I've not recognized the checklist. Is it possible to agree on the CLA for single commits as well?

**Comment by sergiusens** [comment]
This change exposes a problem in our plugin

    snapcraft.internal.sources.errors.SnapcraftRequestError: Network request error: 404 Client Error: Not Found for url: https://github.com/yarnpkg/yarn/releases/download/vv1.10.1/yarn-vv1.10.1.tar.gz

**Comment by fkromer** [comment]
> Well that certainly checks out with the comment right next to it :)

Seems like the code as well as the comment have been sub-optimal :) I'll try to find some time to check it again.

**Comment by sergiusens** [comment]
I will close this PR for the time being considering the previous comment, feel free to reopen once time is available to work on this.

**Pull request closed without merging**
