### PR TITLE
Update rustup link.  Bug: 1662960

### PR DESCRIPTION
**Pull request by cholcombe973**
Rustup has changed over to a new location .

Thanks for helping us make a better Snapcraft!

Checklist:

- Have you signed the contributor licence agreement? Yes
LP: [1662960](https://bugs.launchpad.net/snapcraft/+bug/1662960)
- Have you read our contribution guide? Yes

### CODE REVIEW

**Comment by sergiusens** [comment]
thanks for this but mind fixing the tests? If you do it today it will get into `2.27`

**Comment by cholcombe973** [comment]
Yeah I'm working on them now.

**Comment by cholcombe973** [comment]
@sergiusens I think this should fix it up

**Comment by sergiusens** [comment]
i am seeing things like
Expected: [call(['/tmp/tmp_345efam/parts/test-part/rust/sh.rustup.rs', '--prefix=/tmp/tmp_345efam/parts/test-part/rust', '--disable-sudo', '--save', '--channel=nightly']), call(['/tmp/tmp_345efam/parts/test-part/rust/bin/cargo', 'fetch', '--manifest-path', '/tmp/tmp_345efam/parts/test-part/src/Cargo.toml'])]
Actual: [call(['/tmp/tmp_345efam/parts/test-part/rust/rustup.sh', '--prefix=/tmp/tmp_345efam/parts/test-part/rust', '--disable-sudo', '--save', '--channel=nightly']),
 call(['/tmp/tmp_345efam/parts/test-part/rust/bin/cargo', 'fetch', '--manifest-path', '/tmp/tmp_345efam/parts/test-part/src/Cargo.toml'])]

**Comment by cholcombe973** [comment]
@elopio I do.  It's here: https://github.com/rust-lang-nursery/rustup.rs :)

**Comment by sergiusens** [comment]
@elopio @cholcombe973 reading the script it still doesn't support 64 bit kernels on 32 bit user spaces

**Comment by cholcombe973** [comment]
Ah crap I broke a bunch of things.  This new rustup script doesn't act like the previous one.  Let me work this out.

**Comment by cholcombe973** [comment]
I think i need to abandon this change.  The new rustup is significantly different from the old one and it no longer supports an install prefix.

**Comment by sergiusens** [comment]
should we close this or re-evaluate. I suppose we can propose fixes upstream. They reviewed my stuff pretty quick last time.

**Comment by cholcombe973** [comment]
Yeah I think we should close this for now.  I'll try to work with upstream
to get things fixed before proposing a new PR

**Comment by kyrofa** [comment]
Alright, closing for now.

**Pull request closed without merging**
