### PR TITLE
Fix the package 'python3-distutils' not found on Ubuntu Xenial

### PR DESCRIPTION
**Pull request by khiemdoan**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by cjp256** [comment]
Hello, thanks for this fix.  Though I'm unsure of your environment and how to reproduce.  

1. Are you by chance building with `--destructive-mode` or using docker images?
2. Is the snap you are building using a base of "core" or "core18"?

**Comment by khiemdoan** [comment]
I am building a snap with core18 by docker, snapcore/snapcraft image.
I also found that python3-distutils was only added because it is required from Bionic. Please recheck this pull #2058

**Comment by cjp256** [comment]
Thanks @khiemdoan! @sergiusens what do you think?  Kind of an odd situation to support building core18 on 16.04... should there be an 18.04 docker image to encourage instead when using `base: core18`?

**Comment by khiemdoan** [comment]
I really hope to see a new image based on 18.04, the 16.04 one is too old and the U 20.04 is coming.
Actually, I am rebuilding my old snap, it has used base18 already but now I cannot rebuild it.

**Comment by sergiusens** [comment]
Sorry, this does not fit with the requirements for the plugin. People using docker on hosts not matching the target base could prescribe their dependencies through use of stage-packages.

**Pull request closed without merging**
