### PR TITLE
Add -h short option for help

### PR DESCRIPTION
**Pull request by techtonik**
Fixes https://bugs.launchpad.net/snapcraft/+bug/1807423

https://click.palletsprojects.com/en/7.x/documentation/#help-parameter-customization

- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
Hi there, have you indeed signed the CLA, the tests says no but you marked the checkbox

**Comment by techtonik** [comment]
Rebased and squashed black fixes.

**Comment by techtonik** [comment]
`spread` test times out. No idea what does it do.

**Comment by techtonik** [comment]
@sergiusens thanks!

**Pull request merged**
