### PR TITLE
Do not compile pyc files when installing with pip

### PR DESCRIPTION
**Pull request by SamYaple**
LP: #1621540

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Interesting, I thought when we talked that `--no-compile` did not do the trick, mind removing the fileset in the plugin that removes `pyc` and `__pycache__` if this indeed does work?

**Comment by SamYaple** [comment]
Yea there were still some pyc files that remains, im unsure why just yet. But the --no-compile option still speed up build time and effectively stopped creating most of the pyc files (and that is the documented purpose of --no-compile)

**Comment by sergiusens** [comment]
Try to setup the env with https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE

**Comment by sergiusens** [comment]
ok to test

**Comment by SamYaple** [comment]
Yea that ENV var fixes it for me.

**Comment by sergiusens** [comment]
@SamYaple ok, so different branch then :-)

**Pull request merged**
