### PR TITLE
store: support for more granular store permissions

### PR DESCRIPTION
**Pull request by cprov**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

This change will be released to the production Store on 26th Feb. and is part of a general effort to hardening uploads and related permissions. See https://forum.snapcraft.io/t/isv-questions-about-signing-a-snap/2546 for further steps.

New users of the `enable-ci travis` integration will automatically benefit of this feature, existing users will need to run `enable-ci travis --refresh`.

User of `export-login` will be able to specific fine-grained acls as `package_register, package_push, package_release, package_metrics, package_update` (the most appropriate combination) instead of `package_upload`.

### CODE REVIEW

**Comment by kyrofa** [comment]
As an aside: what happens to old macaroons that are using `package_upload`?

**Comment by cprov** [comment]
@kyrofa Thanks. 

Macaroons with `package_upload` continue to be allowed (issuing and checking), there is no immediate need to deprecate them, as I said it's a permissive 'combo' permission. However, I hope to see a drop on its use once we migrate our services (build, LP, etc).

Documentation update is on its way to production, https://dashboard.staging.snapcraft.io/docs/api/macaroon.html#post--dev-api-acl-

On that topic, please don't land this change in master until this feature is in Store production, I will ping back when it's the case. Do you guys use 'do-not-merge' tag or something similar ?

**Comment by cprov** [comment]
@kyrofa and @sergiusens this change can be safely landed, production Store was finally updated.
Sorry for making you guys wait.

**Comment by cprov** [comment]
@sergiusens or @elopio can you please retry the tests ? the 2 failures were related to our download-service outage yesterday, the problem is solved now.

**Comment by abitrolly** [comment]
Is it possible to document acls for `export-login` help? For `3.0.1` they are not there.
```
Usage: snapcraft export-login [OPTIONS] FILE

  Save login configuration for a store account in FILE.

  This file can then be used to log in to the given account with the
  specified permissions. One can also request the login to be exported to
  stdout instead of a file:

      snapcraft export-login -

  For example, to limit access to the edge channel of any snap the account
  can access:

      snapcraft export-login --channels=edge exported

  Or to limit access to only the edge channel of a single snap:

      snapcraft export-login --snaps=my-snap --channels=edge exported

  To limit access to a single snap, but only until 2019:

      snapcraft export-login --expires="2019-01-01T00:00:00" exported

Options:
  --snaps <snaps>              Comma-separated list of snaps to limit access
  --channels <channels>        Comma-separated list of channels to limit
                               access
  --acls <acls>                Comma-separated list of ACLs to limit access
  --expires <expiration date>  Date/time (in ISO 8601) when this exported
                               login expires
  --help                       Show this message and exit.
```

**Pull request merged**
