### PR TITLE
catkin plugin: add support for ROS Lunar

### PR DESCRIPTION
**Pull request by kyrofa**
Bring the supported ROS distributions to Indigo, Jade, Kinetic, and Lunar (only recently released). No integration/snaps test here, we're adding one to [snapcraft-de-noche](https://github.com/elopio/snapcraft-de-noche/pull/35).

### CODE REVIEW

**Comment by elopio** [comment]
@kalikiana please review this one.

**Comment by elopio** [comment]
This is failing in snapcraft-de-noche: https://travis-ci.org/elopio/snapcraft-de-noche/jobs/245141407

**Comment by kyrofa** [comment]
Ah, that appears to be due to LP [#1677002](https://bugs.launchpad.net/snapcraft/+bug/1677002). The workaround is to just add `lsb-release` to build-packages, so I've one that. Please run it again.

**Comment by elopio** [comment]
It's green now: https://travis-ci.org/elopio/snapcraft-de-noche/jobs/245141407
Waiting for the queue in travis to land this.

**Pull request merged**
