### PR TITLE
feature/maven-targets w/ re-based maven.py

### PR DESCRIPTION
**Pull request by ZenHarbinger**
Re-based maven plugin + test.

Bug Report: https://bugs.launchpad.net/snapcraft/+bug/1599987
Original PR: https://github.com/snapcore/snapcraft/pull/638

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by ZenHarbinger** [comment]
How can I get logs to see what is failing?

**Comment by elopio** [comment]
@ZenHarbinger that's a to-do for our ci system. Here's the error log:
http://paste.ubuntu.com/19233895/

**Comment by ZenHarbinger** [comment]
Thanks, new push coming, hopefully this will catch it.

**Comment by sergiusens** [comment]
Thanks for unmocking glob!

**Pull request merged**
