### PR TITLE
Only discover dependencies once per file.

### PR DESCRIPTION
**Pull request by kyrofa**
Currently snapcraft re-crawls the entire prime directory for dependencies each time a part is primed. If there are enough parts (and enough files to crawl) this can take an inordinate amount of time. This PR fixes LP: [#1575700](https://bugs.launchpad.net/snapcraft/+bug/1575700) by making sure each part has its files crawled exactly once.

### CODE REVIEW

**Comment by sergiusens** [comment]
ok, :+1:

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
This is as green as it will get, for now. I'm sorry for all the noise in the status.

**Pull request merged**
