### PR TITLE
If "source: .." do not copy the current directory into itself.

### PR DESCRIPTION
**Pull request by evandandrea**
This fixes [LP: #1600428](https://bugs.launchpad.net/snapcraft/+bug/1600428) by skipping over the directory containing the snapcraft.yaml when `source: ..`

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
ok to test

**Comment by sergiusens** [comment]
Hmm, this looks weird, @elopio ideas?
```
======================================================================
ERROR: test_pull_with_source_a_parent_of_current_dir (snapcraft.tests.test_sources.TestLocal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.oP2bCg/build.4WQ/real-tree/snapcraft/tests/test_sources.py", line 391, in test_pull_with_source_a_parent_of_current_dir
    local.pull()
  File "/tmp/adt-run.oP2bCg/build.4WQ/real-tree/snapcraft/internal/sources.py", line 353, in pull
    copy_function=common.link_or_copy, ignore=ignore)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/tmp/systemd-private-f5594a71a9ba4ccaac3e284940845926-systemd-timesyncd.service-MUKQz7', 'src/snapcraft/systemd-private-f5594a71a9ba4ccaac3e284940845926-systemd-timesyncd.service-MUKQz7', "[Errno 13] Permission denied: '/tmp/systemd-private-f5594a71a9ba4ccaac3e284940845926-systemd-timesyncd.service-MUKQz7'")]
```

**Comment by elopio** [comment]
The cwd for the test is /tmp/{randomdir}. When you tell it that the source is .., it will try to copy all /tmp into /tmp/{randomdir}/src/snapcraft. Some files in tmp are protected, thus the error.

I suggest to os.chdir('src/snapcraft') before calling pull.

And I think this is missing an integration test. Please take a look at the integration_tests dir, and let me know if you need a hand with this.

Thanks for the code Evan!

**Comment by kyrofa** [comment]
> And I think this is missing an integration test.

Ah, I was going to say just that. Thanks Evan, looks great other than that!

**Comment by evandandrea** [comment]
On it 😄

**Comment by kyrofa** [comment]
@evandandrea do you think you can get that integration test in? Or would you like one of us to take over?

**Comment by kyrofa** [comment]
Closed in favor of #725 due to inactivity.

**Pull request closed without merging**
