### PR TITLE
Add type hinting to file_utils.py

### PR DESCRIPTION
**Pull request by daniellim2000**
Add type hinting support to snapcraft/file_utils.py according to PEP 484

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
What email did you use to sign the CLA with? I recall your first commit to the project going down fine.
The verification is done against the git commit authorship.

Aside from that, this looks pretty good!

**Comment by daniellim2000** [comment]
It's the same email as my github. I just signed it again. Can you check?

**Comment by sergiusens** [comment]
what is your launchpad account?

**Comment by daniellim2000** [comment]
https://launchpad.net/~daniellim0611

But yea it's under a different email.

**Comment by sergiusens** [comment]
Again, given the size I would approve.

Try and work with @elopio today to see about the CLA. 

Here's the output I have
```
sergiusens@mirkwood:~$ cla-check daniellimweesoong2000@gmail.com
Logging into Launchpad...
Checking for a Launchpad account associated with this email address...
The contributor does not have a Launchpad account.
sergiusens@mirkwood:~$ cla-check daniellim0611@gmail.com
Logging into Launchpad...
Checking for a Launchpad account associated with this email address...
Contributor: https://api.launchpad.net/1.0/~daniellim0611
Checking if the contributor has signed the CLA...
The contributor has a Launchpad account, but has not signed the CLA.
```

The first email you have here is not on launchpad which is the one you have on github. I would suggest adding that email to launchpad as well.

**Comment by daniellim2000** [comment]
Alright I just added it

**Comment by sergiusens** [comment]
Are you in the #ubuntu-google room? What is your handle/username there?

**Comment by daniellim2000** [comment]
its daniellimws

**Pull request merged**
