### PR TITLE
ci: disable the travis deploy stage for docs

### PR DESCRIPTION
**Pull request by sergiusens**
Docs generation is broken causing all tests against master to
be broken as well giving us little certainty about the current
code quality.

Signed-off-by: Sergio Schvezov <sergio.schvezov@canonical.com>

### CODE REVIEW

**Comment by kyrofa** [comment]
Why delete the scripts? Don't we want this fixed at some point?

**Comment by sergiusens** [comment]
@kyrofa I would rather re do them when the time comes just like cla-check. I want out of script maze :wink:

**Comment by kalikiana** [comment]
What did break the docs? This isn't a revert of any kind.

**Comment by sergiusens** [comment]
@kalikiana it was always temporary, credentials expired, and they weren't taken care of. I'd rather have nothing than something broken.

Not sure about you, but I get the travis runs for all things that go into master and this thing being red just causes too much noise.

**Pull request merged**
