### PR TITLE
qmake plugin: Stop doing out-of-source builds.

### PR DESCRIPTION
**Pull request by kyrofa**
It doesn't seem well-supported and inexplicably breaks sometimes. This resolves LP: [#1599572](https://bugs.launchpad.net/snapcraft/+bug/1599572).

### CODE REVIEW

**Comment by kyrofa** [comment]
What is this and why is it failing here?

```
======================================================================

ERROR: test_parser_basic (test_parser.TestParser)

test_parser.TestParser.test_parser_basic

----------------------------------------------------------------------

testtools.testresult.real._StringException: Traceback (most recent call last):

  File "/home/travis/build/snapcore/snapcraft/integration_tests/test_parser.py", line 33, in test_parser_basic

    stdout=subprocess.DEVNULL)

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['/home/travis/build/snapcore/snapcraft/bin/snapcraft-parser', '--index', 'https://wiki.ubuntu.com/snapcraft/parts?action=raw', '--output', 'parts.yaml']' returned non-zero exit status 1

----------------------------------------------------------------------
```

**Comment by kyrofa** [comment]
retest this please

**Comment by kyrofa** [comment]
retest this please

**Comment by kyrofa** [comment]
retest this please

**Comment by kyrofa** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Comment by kyrofa** [comment]
> retest this please

Nice try.

**Comment by elopio** [comment]
getting closer...

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
okay, things are moving now!

**Comment by kyrofa** [comment]
retest this please

**Comment by sergiusens** [comment]
ok, I approve

**Pull request merged**
