### PR TITLE
Implementing 'grade' support in snapcraft.yaml

### PR DESCRIPTION
**Pull request by caio1982**
...to assert the built snap quality as per the snappy design doc, see https://docs.google.com/document/d/1MOwyQXkrmMjTJnMsiisfv5Y1lrr5mwNrTxaIbMpNngc/edit#heading=h.4wp4anfwdwtq for the explanation on the purpose of grade.

An upcoming subsequent PR (still depending on snapd changes) will introduce snap-build support that use this new grade parameter.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
I don't know where my comment went to :-/

Thanks for this. The PR has conflicts with master (at the time of the proposal even) which would be good to get sorted.

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by caio1982** [comment]
Hmm snapcraft.tests.test_plugin_dump.DumpPluginTestCase.test_dump_symlinks seems to be failing even without any of my changes. Any idea @sergiusens if this is broken at master?

**Comment by sergiusens** [comment]
@caio1982 don't worry about that one, @elopio is working on a fix. It wasn't broken until recently.

**Comment by sergiusens** [comment]
@caio1982 if you click on Update Branch now, it would all be good wrt the error you saw

**Comment by caio1982** [comment]
All passed, thanks @sergiusens !

**Comment by sergiusens** [comment]
ok to test

**Pull request merged**
