### PR TITLE
Adding Fish shell source and IDEA IDE to gitignore

### PR DESCRIPTION
**Pull request by joedborg**
Thanks for helping us make a better Snapcraft!

Checklist:

- Have you signed the contributor licence agreement?
  https://www.ubuntu.com/legal/contributors
_Yes_

- Is there a reported a bug for the problem you are fixing?
  https://bugs.launchpad.net/snapcraft/
  If there is none, please report it. Once you have the BUG_NUMBER,
  replace it here:

LP: [#1663052](https://bugs.launchpad.net/snapcraft/+bug/1663052)

- Have you read our contribution guide?
  [CONTRIBUTING.md](CONTRIBUTING.md)
_Yes_

### CODE REVIEW

**Comment by kyrofa** [comment]
Um... please fill out the template.

**Comment by joedborg** [comment]
@kyrofa Done - sorry, raised this from an iPhone app that didn't show the template.

**Comment by kyrofa** [comment]
I personally am :-1: on this. Taking this to its logical conclusion, we're maintaining a separate helper script for every exotic shell out there. If this was something integral to snapcraft I might feel differently, but this is just for hitting the staging server while developing store-related changes.

**Comment by joedborg** [comment]
Just a personal opinion; I'm not sure that discarding "exotic" shells (i.e. everything except Bash) is a great idea if you're looking for a wide range of developers.

**Pull request closed without merging**
