### PR TITLE
schema: add missing name item in package-repositories

### PR DESCRIPTION
**Pull request by jc-lab**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [?] Have you successfully run `./runtests.sh tests/unit`?

-----

To fix the error below:

```
Issues while validating snapcraft.yaml: The 'package-repositories[0]' property does not match the required schema: OrderedDict([('type', 'apt'), ('name', 'default'), ('formats', ['deb']), ('architectures', ['amd64', 'i386']), ('components', ['main', 'multiverse']), ('suites', ['$SNAPCRAFT_APT_RELEASE', '$SNAPCRAFT_APT_RELEASE-updates']), ('key-id', '...'), ('url', '...')]) is not valid under any of the given schemas
```

### CODE REVIEW

**Comment by cjp256** [comment]
Hi @jc-lab!

I removed this field (after the initial proposal) because it introduced a bit of complexity without any benefit (over a comment in the yaml).  I do need to update the documentation, and hope to mark this feature stable next week.  Which doc page did you reference? The release notes?

**Comment by jc-lab** [comment]
Hi, @cjp256 

Yes, I have seen this page https://snapcraft.io/docs/release-notes-snapcraft-4-0
I wanted to change the default repository.

The ubuntu repository is a lot slow in my country.

Also, when many builds occur, a lot of traffic can occur in the ubuntu repository, so I wanted to use a local mirror.

**Comment by cjp256** [comment]
@jc-lab you should be able to use the _undocumented_, _unsupported_ environment variable `SNAPCRAFT_BUILD_ENVIRONMENT_PRIMARY_MIRROR` to change it (on first run, otherwise `snapcraft clean` first).

Once this spec lands: https://github.com/snapcore/snapcraft/pull/3262/files the variable to control that knob should be renamed to `SNAPCRAFT_APT_MIRROR` shortly afterwards.

**Comment by jc-lab** [comment]
@cjp256 Thank you!

**Pull request closed without merging**
