### PR TITLE
Replace 'strip' with 'prime' on intro page and step options.

### PR DESCRIPTION
**Pull request by bogdanap**
LP: #1604239

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by kyrofa** [comment]
ok to test

**Comment by kyrofa** [comment]
Thank you for this! Thank you also for making a bug corresponding to this change. You still need to sign the CLA though-- please refer to the [contribution guide](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md) for more information.

**Comment by kyrofa** [comment]
Ah, nevermind on the CLA, I know who you are now :wink: .

**Pull request merged**
