### PR TITLE
Add the TEST_STORE environment variable to the travis script

### PR DESCRIPTION
**Pull request by elopio**
LP: #1623645

### CODE REVIEW

**Comment by cprov** [comment]
@sergiusens and @elopio, I am currently overriding the default .travis.yml configuration on master to make sure docker environment has the right testing switches (TEST_STORE, TEST_USER_EMAIL and TEST_USER_PASSWORD).
It's trivial and safe enough to point it to any testing account, as long as it doesn't have 2FA enabled.

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
I filed this bug to document all about the test scripts.
https://bugs.launchpad.net/snapcraft/+bug/1625236

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
retest this please

**Pull request merged**
