### PR TITLE
docs: add command reference

### PR DESCRIPTION
**Pull request by dboddie**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----
CRAFT-1851

### CODE REVIEW

**Review by mr-cal — APPROVED** [review]

**Comment by sergiusens** [comment]
can we get documentation builds as part of PRs?

**Comment by dboddie** [comment]
> can we get documentation builds as part of PRs?

Yes, when the RTD docs builds are working. I think #4272 fixes breakage caused by an obsolete submodule.

**Comment by sergiusens** [comment]
I have merged the prereq, can you update this branch?

**Comment by dboddie** [comment]
> I have merged the prereq, can you update this branch?

Can you take ownership of the Snapcraft RTD project? The webhook integration won't work properly for me, and I think it's because I don't have the correct permissions on this repo.

**Review by sergiusens — APPROVED** [review]

**Pull request merged**
