### PR TITLE
In the downloader demo test, use https

### PR DESCRIPTION
**Pull request by elopio**
This prevents the redirect from http to https.

LP: #1631463

### CODE REVIEW

**Comment by sergiusens** [comment]
Maybe just use http://start.ubuntu.com/connectivity-check.html

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
@sergiusens all green, it was just a network problem. Do you still want to use the ocnnectivity check?

**Comment by sergiusens** [comment]
I regret that call @elopio ...
`ERR_ACCESS_DENIED` from squid :-/

**Pull request merged**
