### PR TITLE
snap: use rustup on risc-v

### PR DESCRIPTION
**Pull request by lengau**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----
CRAFT-1720

### CODE REVIEW

**Comment by lengau** [comment]
@sergiusens I'm busy building this on an [emulated risc-v QEMU system](https://wiki.ubuntu.com/RISC-V/QEMU) — if all goes well I think this is the best workaround until we move to core22.

**Comment by lengau** [comment]
Marking as ready for review since the latest commit successfully built.

**Comment by lengau** [comment]
@cmatsuoka am I targeting the right branch on this? (Lint & test failures are not related)

**Review by sergiusens — APPROVED** [review]

**Comment by cmatsuoka** [comment]
> @cmatsuoka am I targeting the right branch on this? (Lint & test failures are not related)

Yes if you want the fixes to appear in 7.4.1.

**Pull request merged**
