### PR TITLE
Migration from ubuntu-core to snapcore

### PR DESCRIPTION
**Pull request by sergiusens**
Update debian packaging, docs and links to point to snapcore
instead of ubuntu-core

LP: #1597006

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

### CODE REVIEW

**Comment by kyrofa** [comment]
:+1: Not necessary to change, but worth noting that ubuntu-core/snapcraft is used for several source and yaml test cases.

**Comment by sergiusens** [comment]
@kyrofa yeah, I didn't feel like changing the test cases for this was a good idea

**Comment by kyrofa** [comment]
Yeah that's fair.

**Comment by elopio** [comment]
retest this please

**Comment by sergiusens** [comment]
ok to test ?
retest this please ?
do something!

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
The tests are running but the bot is still not in the team with write access. 

http://162.213.35.179:8080/job/github-snapcraft-autopkgtest-cloud/997/
http://162.213.35.179:8080/job/github-snapcraft-examples-tests-cloud/1089/

**Comment by sergiusens** [comment]
retest this please

**Comment by sergiusens** [comment]
Ok, the java example fails due to unrelated changes, @elopio care to confirm?

**Comment by elopio** [comment]
Confirm. It timed out trying to snap it.

**Pull request merged**
