### PR TITLE
autotools: cross-compile using --host instead of env

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

Take a look at the `configure` output for our autotools cross-compile integration test (I'm doing this by hand, running `snapcraft --target-arch=armhf`):

```
[...]
./configure --prefix= --host=armhf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for armhf-strip... no
checking for strip... strip
[...]
```

Note that it's using the build system's `strip`, not the cross-toolchain's `strip`. What is `armhf-strip` anyway? Nothing, I tell you! We're setting --host to the deb arch instead of the triplet.

Currently the autotools plugin uses the CC and CXX environment variables to force autotools to cross-compile. However, autotools will do this on its own if one sets the --host parameter correctly, and will actually do a better job (e.g. use the cross-toolchain's strip as well).

Remove the environment variables, and set the --host to the target triplet if cross-compiling. More info on how to cross-compile using autotools (including details on --host) can be found [here](https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html).

### CODE REVIEW

**Comment by kyrofa** [comment]
@lool could you take a look at this when you're able?

**Comment by lool** [comment]
I've tested cross-compilations of a hello world snap for armhf and arm64 which failed before and now pass (mainly thanks to the change from --host=armhf to --host=arm-linux-gnueabihf). Test suite also passes (unit and static).

Other changes look good. Removal of the env vars definitions could be a regression if the recipe was working before, but it's better to do this now and see if it's useful to set it or not.

**Comment by kalikiana** [comment]
Some thoughts:
* Shouldn't we test that the correct `strip` is being used now?
* Should we be testing that CC and CXX are set through --host?
* @lool What's "a hello world snap"? The autotools test snap in the snapcraft repo doesn't require this fix at all. It'd be awesome to have something we can test this with.

**Comment by kalikiana** [comment]
Replying to my own points raised above: using gnu-hello as the basis for the integration test does test the bug fix and should be quite sufficient.

**Comment by kalikiana** [comment]
`Logging into Launchpad...
Amount of emails to check the CLA for 3
Checking the CLA for 'malept@users.noreply.github.com'
The contributor does not have a Launchpad account.`

**Comment by kalikiana** [comment]
For the record, failed with:

Collecting docopt==0.6.2 (from -r requirements.txt (line 3))
  Downloading docopt-0.6.2.tar.gz
Collecting file-magic==0.3.0 (from -r requirements.txt (line 4))
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Pull request merged**
