### PR TITLE
catkin plugin: create completely valid environment

### PR DESCRIPTION
**Pull request by kyrofa**
The environment created by the Catkin plugin is really only completely valid at runtime (i.e. when packaged as a snap). It's partially valid at build-time. However, it turns out that as a result of sourcing `setup.sh` (which is required at build-time), various dependencies actually need the valid run-time environment (e.g. `LD_LIBRARY_PATH`, valid `ROS_HOME`, etc.).

This PR fixes LP: [#1674487](https://bugs.launchpad.net/snapcraft/+bug/1674487) by making sure `LD_LIBRARY_PATH` is defined before we source `setup.sh`. It also makes sure `ROS_HOME` is always pointing to a valid place.

### CODE REVIEW

**Comment by kyrofa** [comment]
> Is the turtlebot needed to verify the fix in real life?

No, it can be verified by creating a snap of some Turtlebot-focused software. I thought about making it a snaps test, but if you think the talker/listener ROS snap takes a while, you ain't seen nothin.

**Comment by elopio** [comment]
@kyrofa I'd still be interested in some steps I can run here, even if they take a lot. Maybe you can put them in a gist for testing robotics, and we keep adding things to check once in a while?

**Comment by kyrofa** [comment]
@elopio yeah that's a good idea. [Here you go](https://gist.github.com/kyrofa/c01366d9ef68872efd0d01ee5aa047fe).

**Comment by sergiusens** [comment]
@kyrofa good candidate for the nightlies

**Pull request merged**
