### PR TITLE
dependencies: update click to 8.0.1

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

This is needed for [options with optional values](https://click.palletsprojects.com/en/8.0.x/options/#optional-value).

### CODE REVIEW

**Comment by cjp256** [comment]
Hey Kyle!

We also have a requirements-devel.txt which has the old pinned version.  You can also use tools/freeze-requirements.sh to uprev all deps.  Usually it's fine but with some recent changes in mypy, perhaps not :-)

**Comment by sergiusens** [comment]
@kyrofa nice to see this contribution :-)

I must say you are not following then commit message thing you authored :stuck_out_tongue: https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md

**Comment by kyrofa** [comment]
Yeah I wasn't sure which subsystem to call this :stuck_out_tongue: . @cjp256 shouldn't the -devel requirements be a superset of the runtime requirements? They both look like complete freezes.

**Comment by kyrofa** [comment]
Alright I did as you asked @cjp256, although that script updated all kinds of things.

**Review by cjp256 — APPROVED** [review]
Thanks Kyle! LGTM

**Comment by kyrofa** [comment]
FYI I actually ended up going a different direction for #3554 which doesn't require this anymore. Your call whether or not to merge it.

**Pull request merged**
