### PR TITLE
docker: parametrize risk and OS for image builds (core18 etc)

### PR DESCRIPTION
**Pull request by abitrolly**
This PR allows to change Ubuntu version and risk level of docker image from command line without editing Dockerfiles as advised at https://forum.snapcraft.io/t/creating-docker-images-for-snapcraft/11739

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by abitrolly** [comment]
Rebased.

**Comment by sergiusens** [comment]
This will need conflict resolution work applied. Thanks

**Comment by abitrolly** [comment]
@sergiusens ready.

**Comment by sergiusens** [comment]
Mind telling me how to configure hub.docker.com to automatically build with a matrix of environment variables?

**Comment by abitrolly** [comment]
@sergiusens is there a problem to configure 4 builds with separate environment variables manually? https://docs.docker.com/docker-hub/builds/#environment-variables-for-builds

I don't use Docker Hub autobuilds. I [push images from Travis](https://github.com/yakshaveinc/linux/blob/master/.travis.yml#L38) after their tests are finished. Otherwise you will also need to configure testing on Docker Hub.

The CI configuration for `snapcraft` Docker builds is not using code in repository, but uses files from snap feteched from snapstore API. Building this on every commit is not efficient, and could be improved by using repository tags or by additional checks that could be impossible for Docker Hub, which doesn't know anything about snap versions.

**Comment by abitrolly** [comment]
Rebased. Should work for `core20` too.

**Comment by knocte** [comment]
Shouldn't the X-Ubuntu-Series header be parameterised too? It's hardcoded to 16 now

**Comment by sergiusens** [comment]
We are going to close this PR due to lack of activity.
We don't have anything currently outside of dockerhub that sets up these environments.
If you rather create a docker file independent of these to carry in our repo that people could base out from then that would certainly be welcomed.

**Comment by knocte** [comment]
Lack of activity? WTF? There's lack of activity because there's lack of PR review, which is not to blame to the PR creator.

**Comment by cjp256** [comment]
Sorry about that, you're right.  I'm going to reopen this and see what we can do.   I like the consolidation of the Dockerfiles, but do not fully understand the effects on our CI & images yet.

I started experimenting with the Docker images a couple months ago incorporating the approach taken here as the starting point, but have not yet found the time to get back to it. https://github.com/cjp256/snapcraft-docker-image/blob/master/Dockerfile.

I'll do my best to put some cycles on it next week.

**Comment by abitrolly** [comment]
I've rebased this 5 times already over this year. I feel like I just need to apply to be a product owner for Docker users in this project. )

**Review by sergiusens — APPROVED** [review]

**Comment by sergiusens** [comment]
Thank you for your patience, I will merge as soon as conflicts are resolved (last time :crossed_fingers:)

**Comment by sergiusens** [comment]
> @sergiusens can you answer [#2673 (comment)](https://github.com/snapcore/snapcraft/pull/2673#issuecomment-633197171)?

It should not, the name is unfortunate, but it relates to API version around snaps

**Comment by abitrolly** [comment]
@sergiusens conflict are resolved. Last time! :D

**Comment by abitrolly** [comment]
CLA check service is down. I signed that before

**Comment by sergiusens** [comment]
@MarcusTomlinson fyi, seems CLA check thing is down

**Comment by MarcusTomlinson** [comment]
> @MarcusTomlinson fyi, seems CLA check thing is down

Yeah, was an issue in LP (https://bugs.launchpad.net/launchpad/+bug/1921727), should be fixed now.

**Comment by sergiusens** [comment]
@abitrolly did you use your same email to author the commit?
@MarcusTomlinson any idea how this could fail?

**Comment by abitrolly** [comment]
@sergiusens everything is the same. You can compare with any https://github.com/snapcore/snapcraft/pulls?q=is%3Apr+author%3Aabitrolly+is%3Aclosed

**Comment by MarcusTomlinson** [comment]
> @abitrolly did you use your same email to author the commit?
> @MarcusTomlinson any idea how this could fail?

The GitHub user: https://github.com/abitrolly is not a member of: https://github.com/CanonicalContributorAgreement
The Launchpad user: https://launchpad.net/~abitrolly is not a member of: https://launchpad.net/~contributor-agreement-canonical

Please signed the Canonical Contributor Agreement here: https://ubuntu.com/legal/contributors/agreement

**Comment by abitrolly** [comment]
@MarcusTomlinson but it was. So what happened?

**Comment by sergiusens** [comment]
We are doing better CLA checking now. One minor commit made it into master and our previous check completed skipped the check so it seems you had never signed the CLA. Since this change is bigger than a minor change, we would require you to sign it before merging this. If proceeding, I would be a valid contact which is required in the form.

**Comment by abitrolly** [comment]
Signed again.

**Comment by sergiusens** [comment]
I checked history, and it seems it passed before as there were commits on master which is not longer looked at in the new checks

**Comment by knocte** [comment]
Should the docs be changed now that this PR has been merged?

**Comment by abitrolly** [comment]
@knocte which docs?

**Comment by abitrolly** [comment]
I see that both https://snapcraft.io/docs/snapcraft-docker-images and https://github.com/snapcore/snapcraft/tree/master/docker need to mention how to build for specific Ubuntu `core`. I can only send PR for the contents of `README.md`.

**Comment by abitrolly** [comment]
I sent the PR to update `README.md`, and somebody else needs to take care about the forum/doc contents.

**Pull request merged**
