### PR TITLE
kernel plugin: fix kernel snap layout

### PR DESCRIPTION
**Pull request by lool**
Hi,

This fixes the kernel snap layout for firmware/ and modules/; I've build tested this against the ONL example linked in the bug and prime/ now properly contains a modules/ and firmware/ toplevel.

(Also small fix to list of required packages; these packages were missing on top of a clean Ubuntu 16.04 EC2 instance)

Cheers,
-- Loïc

### CODE REVIEW

**Comment by lool** [comment]
Yup, sorry; I have just fixed the extraneous "lib" in the current path to match the code changes.

BTW, I've noticed that the kernel plugin is a bit fragile, it installs in the build() method and doesn't like when steps are rerun (e.g. if build doesn't complete, the next one will fail to overwrite the previous bits); it looks like it needs a larger refactoring

**Comment by elopio** [comment]
@lool can you please also add a test to manual-tests.md so we don't regress?

**Comment by sergiusens** [comment]
@lool you will need to reauthor your commits with your @canonical.com address or sign the CLA ;-)

**Comment by lool** [comment]
I've done so now (with my @ubuntu.com address)

**Comment by elopio** [comment]
@sergiusens an email in ubuntu.com doesn't mean that the agreement is signed, right?
We know lool so do we really need him to commit with the canonical email?

**Comment by lool** [comment]
(I've also signed the CLA with @ubuntu.com now)

**Pull request merged**
