### PR TITLE
cli: pass remote from container_config to clean method

### PR DESCRIPTION
**Pull request by kalikiana**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----
With `SNAPCRAFT_CONTAINER_BUILDS=foo` running `snapcraft clean` will actually look for a local container, and clean that instead of the container on `foo` or do nothing.

### CODE REVIEW

**Comment by sergiusens** [comment]
have you thoroughly tested this?

**Comment by kalikiana** [comment]
I did some testing from the branch (venv). I'm building a snap now to reproduce the original case.

Also found while testing this that refresh suffers from the same mistake and lack of unit tests... see  #1739 .

**Comment by kalikiana** [comment]
Testing steps:

* Create snapcraft snap from this branch: `snapcraft cleanbuild --remote=helga;  snap install snapcraft_git_amd64.snap --classic --dangerous`
* Enable local container builds: `export SNAPCRAFT_CONTAINER_BUILDS=1`
* Verify no local containers exist: `lxc list`
* Build a test snap `git clone https://github.com/kalikiana/oman.git; cd oman; snapcraft`
* Verify local container: `lxc list`
* Enable remote container builds: `export SNAPCRAFT_CONTAINER_BUILDS=helga`
* Verify no remote containers exist: `lxc list helga:`
* Build a test snap `snapcraft`
* Verify remote container: `lxc list helga:`
* Clean remote container: `snapcraft clean`
* Observe "Deleting helga:snapcraft-oman" in output
* Verify no remote container exists anymore: `lxc list helga:`
* Verify local container wasn't touched: `lxc list`
* Observe "snapcraft-oman | STOPPED" in output

**Comment by kyrofa** [comment]
I want to take this opportunity to say that I don't like the use of "1" to mean "local" whereas that variable can _also_ accept remote names.

Why not make it "local" instead of "1"? That's a valid remote after all.

**Comment by kalikiana** [comment]
@kyrofa You can use "local". But before support for remotes via sshfs we didn't want to allow the name of a remote to be passed. I don't think we want to break that now...

**Comment by kyrofa** [comment]
Can we at least stop using "1" to mean "local" in our docs and conversations? If we start using remote names, people will actually clue into the fact that such a thing is possible, whereas using "1" just looks truthy.

**Pull request merged**
