### PR TITLE
docker: remove snapcraft-wrapper

### PR DESCRIPTION
**Pull request by abitrolly**
Leftover after b292b64d74b643e2ddb3c1ac3f6d6a0bb9baffee.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by abitrolly** [comment]
Rebased.

**Comment by antenore** [comment]
Why the wrapper has been removed? I'using a docker image that uses the wrapper.
Just to understand what it's better to do in these cases.

For reference:

https://hub.docker.com/r/ubuntudesktop/gnome-3-28-1804/dockerfile

Thanks!

**Comment by antenore** [comment]
cc @kenvandine

**Comment by kenvandine** [comment]
@antenore thanks for tagging me.  This has indeed broken the gnome-3-28-1804 docker image.  I plan to fix the image first thing Wednesday.

**Pull request merged**
