### PR TITLE
cli: specify default expiration for export-login

### PR DESCRIPTION
**Pull request by felicianotech**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by felicianotech** [comment]
This PR is a result of this forum convo: https://forum.snapcraft.io/t/snapcraft-export-login-has-a-default-expiration/10209/7

**Comment by felicianotech** [comment]
I saw the follow up, this is still correct.

To answer your question, maybe? Because the help info said nothing about it, I assumed there was no expiration and didn't bother reading the output. I generated the file, base64 encoded it and went about my business.

**Comment by sergiusens** [comment]
ok, then how about a specific time,mention in the help that an expiration will be set and when that is will be returned once logged in?

**Comment by sergiusens** [comment]
Thanks for the effort but I must communicate to you that I am closing this, but feel free to reopen once issues are addressed.

Cheers,
Sergio

**Pull request closed without merging**
