### PR TITLE
set lzo compression by default in kde-neon extension

### PR DESCRIPTION
**Pull request by jriddell**
- [x ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x ] Have you successfully run `./runtests.sh static`?
- [x ] Have you successfully run `./runtests.sh tests/unit`?

enable lzo compression in kde-neon extension by default

from chatting with ppd and post at https://forum.snapcraft.io/t/lzo-for-platform-snaps/27501

-----

### CODE REVIEW

**Comment by ppd** [comment]
Is this something we still want to do? Electron-builder switch to LZO by default, too.

**Comment by sergiusens** [comment]
sorry @ppd for the delays, let's do this

**Review by sergiusens — APPROVED** [review]

**Comment by sergiusens** [comment]
want me to finalize the PR?

**Comment by ppd** [comment]
> want me to finalize the PR?

@jriddell ping

**Comment by sergiusens** [comment]
@igorljubuncic maybe you want to quickly profile the performance gains of switching to lzo for kde apps (the heavy and light ones)?

**Comment by igorljubuncic** [comment]
Yes, this would be a useful test!

**Comment by ppd** [comment]
@igorljubuncic The same idea would apply well to Gnome-based snaps. They could also be compressed as LZO by default. Furthermore, what about compressing the platform snaps as LZO? The kde platform snaps switched to LZO and saw read performance gains, which propagated through to the app snaps.

**Comment by igorljubuncic** [comment]
@ppd yes, but the best thing is to do it systematically, step by step. I spoke with @jriddell and he will build several kde snaps as well as the framework with/without lzo, and then we can run tests and examine the performance. Then, this can be further extended to additional snaps.

**Comment by jriddell** [comment]
kblocks
https://snapcraft.io/kblocks
rev 113 in beta channel is xz  (4.8MB)
rev 114 in edge channel is lzo (6.2MB)

gcompris
https://snapcraft.io/gcompris
rev 35 in beta channel is xz (152MB)
rev 36 in edge channel is lzo (186MB)

**Comment by jriddell** [comment]
kde-frameworks-5-qt-5-15-3-core20
rev 12 in beta is xz
rev 13 in edge is lzo

**Comment by sergiusens** [comment]
If you don't mind, I am going to prep this PR for release

**Pull request merged**
