### PR TITLE
add github action ci/cd

### PR DESCRIPTION
**Pull request by sd-hd**
Hi,

i added a github action ci/cd to snapcraft.

Don't know if this is useful for you ;-)

### CODE REVIEW

**Comment by sergiusens** [comment]
You seem to have based this on @jhenstridge 's work and I agreed with him that we would integrate this in some other location https://forum.snapcraft.io/t/call-for-testing-github-action-for-snapcrtaft/14930/17

**Comment by sd-hd** [comment]
@sergiusens 
The point is, that it's difficult to get a `classic` snap to the store.
For testing and sway, i use a patched `snapd`

**Comment by sd-hd** [comment]
Maybe, we could add an environment variable, to disable the upload on github.

**Comment by sd-hd** [comment]
added this secrets, to make the workflow controlable:
* GITHUB_ACTION_ENABLED
* PUBLISH_GITHUB
* PUBLISH_SNAPCRAFT_STORE

**Comment by sd-hd** [comment]
@MatteoGheza 
@sergiusens 
Could you look at this discussion ? 
https://github.com/snapcore/snapd/pull/8143

**Comment by jhenstridge** [comment]
Similar to your snapd PR, it is unlikely that Snapcraft will switch to using Github Actions to manage the release process any time soon.

Currently Snapcraft is published to the store for six different architectures, and this workflow would only produce an amd64 build.  It is important that Snapcraft is available on these additional architectures, since it enables building snaps on those architectures.

So I'd encourage you to start small, and consider what value you're adding on top of the existing CI and deployment processes.

**Comment by sd-hd** [comment]
> So I'd encourage you to start small, and consider what value you're adding on top of the existing CI and deployment processes.

Like @anonymouse64 wrote: It would be nice, if any PR push a snap for testing into the PR's comment. For download and quick testing.

At the moment, i don't know how good cross-compiling inside github-actions works. But i think, this could also be possible on some time. 

The upload to the store is with "environment secrets" en- and disable.

@jhenstridge 
currently i have time to experiment. And maybe it's useful for you, too ;-)

**Comment by sergiusens** [comment]
Thanks for the contribution. If you can use the new endpoint and get PRs to publish to comments, please feel free to reopen this PR with that functionality. At the time being, this PR does not fit the needs we have as we currently publish for all architectures when the PR is hosted on snapcore.

**Pull request closed without merging**
