### PR TITLE
Restore cmake artifacts

### PR DESCRIPTION
**Pull request by cjp256**
- [ ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [ ] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Comment by sergiusens** [comment]
Are we bringing this back from legacy? I would suggest not and relying on use of override-build or adding the proper targets to the makefiles.

**Comment by cjp256** [comment]
@sergiusens That's certainly an option and I'll defer to your judgement.  I assumed when you handed me the ticket that you wanted me to "fix" it :)

While I think the rationale for adding the install target is fair:
(1) I think the challenge may be if it's an upstream outside of your control... 
(2) The question of consistency between `make` and `cmake` plugin?  Why one and not the other?

Either way, I would suggest we keep the two file_utils.link_or_copy_files commits.  I bet there are other areas in the codebase that could use it as well.

**Comment by sergiusens** [comment]
OK on commit 1 and 2... the adding an install target rationale can apply to all build systems, so having it for a few does not seem to provide a consistent picture, it is quite unfortunate that we failed to remove this from the make plugin before transitioning

**Comment by cjp256** [comment]
Closing, will open new one for file_utils.link_or_copy_files

**Pull request closed without merging**
