### PR TITLE
catkin plugin: check for pip packages in part only

### PR DESCRIPTION
**Pull request by kyrofa**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

Currently the Catkin plugin generates a sitecustomize.py if:

1. pip is setup
2. pip packages have been pulled

This is good in theory, but pip will be considered setup even if it's only available in the staging area, and `pip list` will return packages in the staging area, which means Catkin will pretty much try to generate a sitecustomize.py if there are any Python parts in the snap, even if it doesn't use pip itself.

This PR fixes LP: [#1730248](https://bugs.launchpad.net/snapcraft/+bug/1730248) by making sure it checks `pip list --user` rather than just `pip list`. This will ensure it only looks for pip packages installed by the Catkin part rather than all parts in the snap.

### CODE REVIEW

**Comment by kyrofa** [comment]
There are two tests in `integration_tests/test_catkin.py`. Look at the timing difference when #1530 is not applied:

```
$ time ./runtests.sh integration test_catkin.py
test_catkin_part_builds_after_python_part (test_catkin.CatkinTestCase)
test_catkin.CatkinTestCase.test_catkin_part_builds_after_python_part ... ok
test_shared_ros_builds_without_catkin_in_underlay (test_catkin.CatkinTestCase)
test_catkin.CatkinTestCase.test_shared_ros_builds_without_catkin_in_underlay ... ok

----------------------------------------------------------------------
Ran 2 tests in 691.160s

OK
Everything passed

real	11m31.699s
user	4m34.224s
sys	0m44.168s
```

Versus when it's applied:

```
$ time ./runtests.sh integration test_catkin.py
test_catkin_part_builds_after_python_part (test_catkin.CatkinTestCase)
test_catkin.CatkinTestCase.test_catkin_part_builds_after_python_part ... ok
test_shared_ros_builds_without_catkin_in_underlay (test_catkin.CatkinTestCase)
test_catkin.CatkinTestCase.test_shared_ros_builds_without_catkin_in_underlay ... ok

----------------------------------------------------------------------
Ran 2 tests in 504.015s

OK
Everything passed

real	8m24.548s
user	4m18.064s
sys	0m37.372s
```

That's only two tests, and on my decent hardware rather than Travis. I think we need #1530.

**Comment by kyrofa** [comment]
> Pondering if we can have more test coverage for this part of the python plugin although I'm struggling to see exactly what would reproduce a problem that isn't catkin-specific...

Indeed, this is catkin-specific. `pip list` is used in the Python plugin to ensure that it doesn't re-pull dependencies that are already satisfied by another part (i.e. already in the staging area). In the Catkin plugin, we're using `pip list` to check and see if THIS PART specifically has pulled any pip packages. To that end, Catkin is the only plugin that needs `pip list --user` right now.

**Comment by sergiusens** [comment]
I'll update the branch @elopio but I'd say, move it now.

**Comment by kyrofa** [comment]
Local zesty adt finished with two seemingly unrelated errors:

```
======================================================================
ERROR: test_install_and_execution (test_dotnet_snap.DotnetTestCase)
test_dotnet_snap.DotnetTestCase.test_install_and_execution
----------------------------------------------------------------------
testtools.testresult.real._StringException: output: {{{
Starting snapcraft 2.34 from /usr/lib/python3/dist-packages/snapcraft/cli.
Setting up part 'dotnet-hello' with plugin 'dotnet' and properties {'prime': [], 'stage': [], 'source': '.', 'plugin': 'dotnet'}.
Preparing to pull dotnet-hello 
Fetching stage-packages {'liblttng-ust0', 'lldb', 'libgssapi-krb5-2', 'libssl1.0.0', 'libcurl3', 'libc6', 'libgcc1', 'libicu55', 'libcurl3-gnutls', 'libunwind8', 'zlib1g'}

Get:1 file:/tmp/adt-run.f2VGmt/binaries  InRelease

Ign file:/tmp/adt-run.f2VGmt/binaries  InRelease

Get:2 file:/tmp/adt-run.f2VGmt/binaries  Release [814 B]

Get:3 file:/tmp/adt-run.f2VGmt/binaries  Release [814 B]

Get:4 file:/tmp/adt-run.f2VGmt/binaries  Release.gpg

Ign file:/tmp/adt-run.f2VGmt/binaries  Release.gpg

Get:5 file:/tmp/adt-run.f2VGmt/binaries  Packages [3123 B]

Get:6 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]

Get:7 http://archive.ubuntu.com/ubuntu zesty InRelease [243 kB]

Get:8 http://security.ubuntu.com/ubuntu zesty-security/multiverse Sources [1352 B]

Get:9 http://security.ubuntu.com/ubuntu zesty-security/restricted Sources [964 B]

Get:10 http://archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]

Get:11 http://security.ubuntu.com/ubuntu zesty-security/main Sources [58.9 kB]

Get:12 http://archive.ubuntu.com/ubuntu zesty-backports InRelease [89.2 kB]

Get:13 http://security.ubuntu.com/ubuntu zesty-security/universe Sources [28.3 kB]

Get:14 http://archive.ubuntu.com/ubuntu zesty/restricted Sources [5064 B]

Get:15 http://security.ubuntu.com/ubuntu zesty-security/main amd64 Packages [160 kB]

Get:16 http://archive.ubuntu.com/ubuntu zesty/main Sources [912 kB]

Get:17 http://security.ubuntu.com/ubuntu zesty-security/main Translation-en [74.5 kB]

Get:18 http://security.ubuntu.com/ubuntu zesty-security/restricted amd64 Packages [2436 B]

Get:19 http://archive.ubuntu.com/ubuntu zesty/multiverse Sources [184 kB]

Get:20 http://security.ubuntu.com/ubuntu zesty-security/restricted Translation-en [1352 B]

Get:21 http://security.ubuntu.com/ubuntu zesty-security/universe amd64 Packages [84.0 kB]

Get:22 http://archive.ubuntu.com/ubuntu zesty/universe Sources [8459 kB]

Get:23 http://security.ubuntu.com/ubuntu zesty-security/universe Translation-en [55.9 kB]

Get:24 http://security.ubuntu.com/ubuntu zesty-security/multiverse amd64 Packages [2968 B]

Get:25 http://security.ubuntu.com/ubuntu zesty-security/multiverse Translation-en [1744 B]

Get:26 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages [1207 kB]

Get:27 http://archive.ubuntu.com/ubuntu zesty/main Translation-en [577 kB]

Get:28 http://archive.ubuntu.com/ubuntu zesty/restricted amd64 Packages [8672 B]

Get:29 http://archive.ubuntu.com/ubuntu zesty/restricted Translation-en [2724 B]

Get:30 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages [8068 kB]

Get:31 http://archive.ubuntu.com/ubuntu zesty/universe Translation-en [4671 kB]

Get:32 http://archive.ubuntu.com/ubuntu zesty/multiverse amd64 Packages [154 kB]

Get:33 http://archive.ubuntu.com/ubuntu zesty/multiverse Translation-en [109 kB]

Get:34 http://archive.ubuntu.com/ubuntu zesty-updates/restricted Sources [1436 B]

Get:35 http://archive.ubuntu.com/ubuntu zesty-updates/main Sources [99.4 kB]

Get:36 http://archive.ubuntu.com/ubuntu zesty-updates/universe Sources [63.8 kB]

Get:37 http://archive.ubuntu.com/ubuntu zesty-updates/multiverse Sources [4700 B]

Get:38 http://archive.ubuntu.com/ubuntu zesty-updates/main amd64 Packages [235 kB]

Get:39 http://archive.ubuntu.com/ubuntu zesty-updates/main Translation-en [109 kB]

Get:40 http://archive.ubuntu.com/ubuntu zesty-updates/restricted amd64 Packages [2772 B]

Get:41 http://archive.ubuntu.com/ubuntu zesty-updates/restricted Translation-en [1516 B]

Get:42 http://archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages [156 kB]

Get:43 http://archive.ubuntu.com/ubuntu zesty-updates/universe Translation-en [88.2 kB]

Get:44 http://archive.ubuntu.com/ubuntu zesty-updates/multiverse amd64 Packages [11.8 kB]

Get:45 http://archive.ubuntu.com/ubuntu zesty-updates/multiverse Translation-en [6280 B]

Get:46 http://archive.ubuntu.com/ubuntu zesty-backports/main Sources [1192 B]

Get:47 http://archive.ubuntu.com/ubuntu zesty-backports/universe Sources [2308 B]

Get:48 http://archive.ubuntu.com/ubuntu zesty-backports/main amd64 Packages [1712 B]

Get:49 http://archive.ubuntu.com/ubuntu zesty-backports/main Translation-en [668 B]

Get:50 http://archive.ubuntu.com/ubuntu zesty-backports/universe amd64 Packages [3092 B]

Get:51 http://archive.ubuntu.com/ubuntu zesty-backports/universe Translation-en [1400 B]

Fetched 26.1 MB in 6s (4300 kB/s)
Marking 'liblttng-ust0' (and its dependencies) to be fetched
Marking 'lldb' (and its dependencies) to be fetched
Marking 'libgssapi-krb5-2' (and its dependencies) to be fetched
Marking 'libssl1.0.0' (and its dependencies) to be fetched
Marking 'libcurl3' (and its dependencies) to be fetched
Marking 'libc6' (and its dependencies) to be fetched
Marking 'libgcc1' (and its dependencies) to be fetched
Marking 'libicu55' (and its dependencies) to be fetched
Exception occurred: PackageNotFoundError('libicu55',)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 194, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.5/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'libicu55'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snapcraft/internal/repo/_deb.py", line 222, in _mark_install
    apt_cache[name_arch].mark_install()
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 204, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'libicu55'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snapcraft/internal/pluginhandler/__init__.py", line 230, in _fetch_stage_packages
    stage_packages)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/repo/_deb.py", line 294, in get
    self._mark_install(apt_cache, package_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/repo/_deb.py", line 224, in _mark_install
    raise errors.PackageNotFoundError(name)
snapcraft.internal.repo.errors.PackageNotFoundError: The package 'libicu55' was not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.34', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/__init__.py", line 124, in run
    ctx.forward(lifecyclecli.commands['snap'])
  File "/usr/lib/python3/dist-packages/click/core.py", line 552, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 140, in snap
    project_options, directory=directory, output=output)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_packer.py", line 45, in snap
    execute('prime', project_options)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 80, in execute
    _Executor(config, project_options).run(step, part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 175, in run
    self._run_step(step, part, part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 205, in _run_step
    getattr(part, 'prepare_{}'.format(step))()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/pluginhandler/__init__.py", line 244, in prepare_pull
    self._fetch_stage_packages()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/pluginhandler/__init__.py", line 232, in _fetch_stage_packages
    raise errors.StagePackageDownloadError(self.name, e.message)
snapcraft.internal.errors.StagePackageDownloadError: Error downloading stage packages for part 'dotnet-hello': The package 'libicu55' was not found.
}}}

Traceback (most recent call last):
  File "/tmp/adt-run.f2VGmt/build.EWv/real-tree/integration_tests/snapd/test_dotnet_snap.py", line 32, in test_install_and_execution
    self.run_snapcraft(project_dir='dotnet-hello')
  File "/tmp/adt-run.f2VGmt/build.EWv/real-tree/integration_tests/__init__.py", line 133, in run_snapcraft
    env=env)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['snapcraft', '-d']' returned non-zero exit status 2
```

That's a legit error. I logged LP: [#1732065](https://bugs.launchpad.net/snapcraft/+bug/1732065) for this. We either need to make it work on non-xenial, or skip those tests on non-xenial.

And then that good-old plainbox one:

```
test_plainbox.PlainboxTestCase.test_install_and_execution ... --- Logging error ---
Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/cmd_run.py", line 44, in invoked
    self.provider_loader, self.config_loader, ns, ns.color).run()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 367, in run
    return self.do_normal_sequence()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 379, in do_normal_sequence
    self.create_manager(None)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 619, in create_manager
    self._manager = SessionManager.create_with_unit_list(all_units)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/manager.py", line 290, in create_with_unit_list
    storage = SessionStorage.create(repo.location, legacy_mode)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/storage.py", line 286, in create
    os.makedirs(base_dir)
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/sessions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/logs/crash.log'
Call stack:
  File "/snap/plainbox-simple/x1/bin/plainbox", line 11, in <module>
    sys.exit(main())
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/box.py", line 123, in main
    raise SystemExit(PlainBoxTool().main(argv))
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 324, in main
    return self.dispatch_and_catch_exceptions(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 597, in dispatch_and_catch_exceptions
    self.get_exec_name(), ns, exc_info=1)
Message: 'Executable %r invoked with %r has crashed'
Arguments: ('plainbox', Namespace(color=None, command=<plainbox.impl.commands.cmd_run.RunCommand object at 0x7fbdd4631c18>, debug_console=False, debug_interrupt=False, dont_suppress_output=False, dry_run=False, exclude_pattern_list=[], include_pattern_list=[' com.example::.*'], log_level=None, non_interactive=False, output_file=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>, output_format='com.canonical.plainbox::text', output_options='', pdb=False, test_plan=None, trace=[], transport=None, transport_options=None, transport_where=None, whitelist=[]))
CRITICAL plainbox.crashes: Executable 'plainbox' invoked with Namespace(color=None, command=<plainbox.impl.commands.cmd_run.RunCommand object at 0x7fbdd4631c18>, debug_console=False, debug_interrupt=False, dont_suppress_output=False, dry_run=False, exclude_pattern_list=[], include_pattern_list=[' com.example::.*'], log_level=None, non_interactive=False, output_file=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>, output_format='com.canonical.plainbox::text', output_options='', pdb=False, test_plan=None, trace=[], transport=None, transport_options=None, transport_where=None, whitelist=[]) has crashed
Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/cmd_run.py", line 44, in invoked
    self.provider_loader, self.config_loader, ns, ns.color).run()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 367, in run
    return self.do_normal_sequence()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 379, in do_normal_sequence
    self.create_manager(None)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 619, in create_manager
    self._manager = SessionManager.create_with_unit_list(all_units)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/manager.py", line 290, in create_with_unit_list
    storage = SessionStorage.create(repo.location, legacy_mode)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/storage.py", line 286, in create
    os.makedirs(base_dir)
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/sessions'
--- Logging error ---
Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/cmd_run.py", line 44, in invoked
    self.provider_loader, self.config_loader, ns, ns.color).run()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 367, in run
    return self.do_normal_sequence()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 379, in do_normal_sequence
    self.create_manager(None)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 619, in create_manager
    self._manager = SessionManager.create_with_unit_list(all_units)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/manager.py", line 290, in create_with_unit_list
    storage = SessionStorage.create(repo.location, legacy_mode)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/storage.py", line 286, in create
    os.makedirs(base_dir)
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/sessions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/handlers.py", line 185, in shouldRollover
    self.stream = self._open()
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/logs/problem.log'
Call stack:
  File "/snap/plainbox-simple/x1/bin/plainbox", line 11, in <module>
    sys.exit(main())
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/box.py", line 123, in main
    raise SystemExit(PlainBoxTool().main(argv))
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 324, in main
    return self.dispatch_and_catch_exceptions(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 597, in dispatch_and_catch_exceptions
    self.get_exec_name(), ns, exc_info=1)
Message: 'Executable %r invoked with %r has crashed'
Arguments: ('plainbox', Namespace(color=None, command=<plainbox.impl.commands.cmd_run.RunCommand object at 0x7fbdd4631c18>, debug_console=False, debug_interrupt=False, dont_suppress_output=False, dry_run=False, exclude_pattern_list=[], include_pattern_list=[' com.example::.*'], log_level=None, non_interactive=False, output_file=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>, output_format='com.canonical.plainbox::text', output_options='', pdb=False, test_plan=None, trace=[], transport=None, transport_options=None, transport_where=None, whitelist=[]))
Traceback (most recent call last):
  File "/snap/plainbox-simple/x1/bin/plainbox", line 11, in <module>
    sys.exit(main())
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/box.py", line 123, in main
    raise SystemExit(PlainBoxTool().main(argv))
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 324, in main
    return self.dispatch_and_catch_exceptions(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 560, in dispatch_and_catch_exceptions
    return self.dispatch_command(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/clitools.py", line 556, in dispatch_command
    return ns.command.invoked(ns)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/cmd_run.py", line 44, in invoked
    self.provider_loader, self.config_loader, ns, ns.color).run()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 367, in run
    return self.do_normal_sequence()
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 379, in do_normal_sequence
    self.create_manager(None)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/commands/inv_run.py", line 619, in create_manager
    self._manager = SessionManager.create_with_unit_list(all_units)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/manager.py", line 290, in create_with_unit_list
    storage = SessionStorage.create(repo.location, legacy_mode)
  File "/snap/plainbox-simple/x1/lib/python3.5/site-packages/plainbox/impl/session/storage.py", line 286, in create
    os.makedirs(base_dir)
  File "/snap/plainbox-simple/x1/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/autopkgtest_tmp/tmph97exw4w/.cache/plainbox/sessions'
ERROR
```

That

**Comment by kyrofa** [comment]
Would like a xenial:armhf run here. Waiting on #1731 to be merged in order for those to pass. Then assuming xenial:armhf is green here, I think it's good.

**Comment by kyrofa** [comment]
Darn, I didn't realize that armhf didn't install snaps. So that needs to run, but I'm also running xenial:amd64 locally now.

**Comment by kyrofa** [comment]
Got a successful local pass on xenial:amd64. Only failure was LP: [#1732076](https://bugs.launchpad.net/bugs/1732076).

**Comment by sergiusens** [comment]
lesson is, don't move tests around so late in the game

**Comment by sergiusens** [comment]
xenial-armhf has no use in running again, it passed and it won't exercise what is to be tested

**Pull request merged**
