### PR TITLE
Extending the created yaml from `snapcraft init`

### PR DESCRIPTION
**Pull request by wandrewkeech**
This patch corrects the indentation, and extends the default properties in the `snapcraft.yaml` created by the `init` option to provide a better minimal example.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
I am sorry, but this does not produce a project you can build by default as is; can you open up a discussion in a bug report please?

**Comment by wandrewkeech** [comment]
Apologies, had a standing launchpad bug listed, but did not cross reference this new PR and that bug.

https://bugs.launchpad.net/snapcraft/+bug/1604504

**Pull request closed without merging**
