### PR TITLE
Wishlist feature/maven-targets branch for snapcraft.

### PR DESCRIPTION
**Pull request by ZenHarbinger**
Accidental delete of my branch of code. Le sigh.
Have signed contributor form.
Have filled out bug:
https://bugs.launchpad.net/snapcraft/+bug/1599987

Not sure how to get status to Wishlist.

### CODE REVIEW

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by snappy-m-o** [comment]
Can one of the admins verify this patch?

**Comment by sergiusens** [comment]
Hi there, this looks good, however I cannot land this as it has conflicts with another branch that landed.

**Comment by ZenHarbinger** [comment]
OK, I'll merge and re-go.

**Pull request closed without merging**
