### PR TITLE
Add flutter-stable and -beta extension variants

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
Implements: https://git.io/JqZuf
Fixes: https://github.com/canonical/flutter-snap/issues/33

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh tests/unit`?

-----

### CODE REVIEW

**Review by sergiusens — COMMENTED** [review]
Looks good, the only thing I would ask for is a spread test to easily detect upstream changes that would afect us.

You can make a variant out of tests/spread/plugins/v1/flutter/run/task.yaml

**Comment by MarcusTomlinson** [comment]
@sergiusens 18.04 spread tests timed out, does this usually happen?

**Review by sergiusens — APPROVED** [review]
Awesome! Thanks!

**Review by cjp256 — COMMENTED** [review]
LGTM, though is there a difference between "flutter" and "flutter-stable"?  Any reason we need both?

**Comment by MarcusTomlinson** [comment]
> LGTM, though is there a difference between "flutter" and "flutter-stable"? Any reason we need both? FWIW the spread test does not exercise "flutter".

Yeah it's a good point. I propose then that we remove the plain "flutter" extension variant.

**Review by cjp256 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
