### PR TITLE
Check the older ubuntu-core snap name for core dynamic linker.

### PR DESCRIPTION
**Pull request by thomir**
Fixes LP: [#1650946](https://bugs.launchpad.net/snapcraft/+bug/1650946) for those of us who have the older 'ubuntu-core' snap installed.

### CODE REVIEW

**Comment by elopio** [comment]
@sergiusens can you just quickly confirm that the new ubuntu-core will work the same for classic snaps?

**Comment by kyrofa** [comment]
Yeah make sure @sergiusens takes a look, [he seemed to only want core](https://github.com/snapcore/snapcraft/pull/949#discussion_r91182679).

**Comment by sergiusens** [comment]
I am sorry to say this won't work moving forward, the requirement is to have `core` only, `ubuntu-core` is deprecated and going away and once it does, all these snaps will just fail to work.

Thanks for the PR

**Comment by thomir** [comment]
I'm confused - which snaps will fail to work? Surely this is something that has an effect at the build-time of snaps, not at the run-time?

By all means close the PR, especially if there's a migration path coming for people who have 'ubuntu-core' installed. If there's no migration path however, snapcraft becomes unusable to everyone in this situation.

Can you please elaborate on what your plan is to fix this?

**Comment by sergiusens** [comment]
@thomir runtime is also affected, the linker is forced to be the one in the snap at runtime as well

```
$ readelf -a /snap/vim/current/bin/vim |grep INTERP -A3
  INTERP         0x0000000000000238 0x0000000000400238 0x0000000000400238
                 0x0000000000000033 0x0000000000000033  R      1
      [Requesting program interpreter: /snap/core/current/lib/x86_64-linux-gnu/ld-2.23.so]
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
```

**Comment by niemeyer** [comment]
The proper fix for this will be worked on over the next few days. We'll migrate ubuntu-core to core.

**Comment by kyrofa** [comment]
> By all means close the PR, especially if there's a migration path coming for people who have 'ubuntu-core' installed. If there's no migration path however, snapcraft becomes unusable to everyone in this situation.

Last I heard the snapd folks were working on a migration plan.

**Comment by thomir** [comment]
Great, thanks @niemeyer !

**Pull request closed without merging**
