### PR TITLE
python plugins: add process-dependency-links option

### PR DESCRIPTION
**Pull request by sergiusens**
This will run pip install with --process-dependency-links as per [0].

[0] https://pip.pypa.io/en/stable/reference/pip_wheel/#cmdoption--process-dependency-links

LP: #1614186

### CODE REVIEW

**Comment by josepht** [comment]
Looks sensible to me.

**Comment by elopio** [comment]
retest this please

**Comment by elopio** [comment]
restest this please

**Comment by sergiusens** [comment]
retest this please

**Comment by elopio** [comment]
:+1: lgtm

**Pull request merged**
