### PR TITLE
tests: move the plainbox test to the integration suite

### PR DESCRIPTION
**Pull request by elopio**
- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] If this is a bugfix. Have you checked that there is a bug report open for the issue you are trying to fix on [bug reports](https://bugs.launchpad.net/snapcraft)?
- [x] If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?
- [x] Have you successfully run `./runtests.sh static`?
- [x] Have you successfully run `./runtests.sh unit`?

-----

### CODE REVIEW

**Comment by elopio** [comment]
Hey @jocave, the plainbox test started to fail:
```
testtools.matchers._impl.MismatchError: !=:
reference = '''\
2013.com.canonical.plainbox::collect-manifest
2013.com.canonical.plainbox::manifest
2016.com.example::always-fail
2016.com.example::always-pass
'''
actual    = '''\
com.canonical.plainbox::collect-manifest
com.canonical.plainbox::manifest
2016.com.example::always-fail
2016.com.example::always-pass
'''
```

Should we just remove the 2013 from the expected result?

Btw, we are moving things around, like in this PR, so we catch errors like this one a little earlier.

**Comment by jocave** [comment]
Hi @elopio,

Yes plainbox has started internally removing the year prefix from namespaces (it gave the wrong impression to people new to the tests). The quick fix is to remove the '2013.' as you have noted. It might be better to remove the year from all the sample providers in the test suite though.

**Comment by kyrofa** [comment]
Thanks for the input @jocave-- @elopio I pushed a commit that removes the year as suggested. Tests pass locally.

**Comment by elopio** [comment]
Thanks @jocave and @kyrofa. I removed a couple of years from the manage.py, and now this is ready to go.

**Comment by kyrofa** [comment]
Whoops, sorry @elopio apparently I don't know how to use git.

**Comment by kyrofa** [comment]
Running autopkgtest here to double-check.

**Pull request merged**
